from copy import deepcopy


COMPARISON_TOPICS = [
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_fastest_land_animals",
        "subject_vi": "Top 5 con vật chạy nhanh nhất trên cạn",
        "subject_en": "Top 5 fastest land animals",
        "comparison_angle": "speed",
        "items": [
            {"rank": 1, "name_vi": "Báo Săn", "name_en": "Cheetah", "stat": "110 km/h"},
            {"rank": 2, "name_vi": "Linh Dương Sừng Nhánh", "name_en": "Pronghorn", "stat": "88 km/h"},
            {"rank": 3, "name_vi": "Linh Dương Springbok", "name_en": "Springbok", "stat": "88 km/h"},
            {"rank": 4, "name_vi": "Linh Dương Đầu Bò Xanh", "name_en": "Blue wildebeest", "stat": "80 km/h"},
            {"rank": 5, "name_vi": "Sư Tử", "name_en": "Lion", "stat": "80 km/h"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_tallest_land_animals",
        "subject_vi": "Top 5 loài động vật cao nhất trên cạn",
        "subject_en": "Top 5 tallest land animals",
        "comparison_angle": "height",
        "items": [
            {"rank": 1, "name_vi": "Hươu Cao Cổ", "name_en": "Giraffe", "stat": "5.5 m"},
            {"rank": 2, "name_vi": "Voi Châu Phi", "name_en": "African elephant", "stat": "4.0 m"},
            {"rank": 3, "name_vi": "Lạc Đà Một Bướu", "name_en": "Dromedary camel", "stat": "2.3 m"},
            {"rank": 4, "name_vi": "Nai Sừng Tấm", "name_en": "Moose", "stat": "2.1 m"},
            {"rank": 5, "name_vi": "Ngựa Shire", "name_en": "Shire horse", "stat": "2.0 m"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_heaviest_land_animals",
        "subject_vi": "Top 5 động vật trên cạn nặng nhất",
        "subject_en": "Top 5 heaviest land animals",
        "comparison_angle": "weight",
        "items": [
            {"rank": 1, "name_vi": "Voi Châu Phi", "name_en": "African elephant", "stat": "6000 kg"},
            {"rank": 2, "name_vi": "Voi Châu Á", "name_en": "Asian elephant", "stat": "5000 kg"},
            {"rank": 3, "name_vi": "Tê Giác Trắng", "name_en": "White rhinoceros", "stat": "2300 kg"},
            {"rank": 4, "name_vi": "Hà Mã", "name_en": "Hippopotamus", "stat": "1800 kg"},
            {"rank": 5, "name_vi": "Hươu Cao Cổ", "name_en": "Giraffe", "stat": "1200 kg"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_biggest_birds",
        "subject_vi": "Top 5 loài chim lớn nhất thế giới",
        "subject_en": "Top 5 biggest birds in the world",
        "comparison_angle": "size",
        "items": [
            {"rank": 1, "name_vi": "Đà Điểu Châu Phi", "name_en": "Ostrich", "stat": "156 kg"},
            {"rank": 2, "name_vi": "Đà Điểu Somali", "name_en": "Somali ostrich", "stat": "130 kg"},
            {"rank": 3, "name_vi": "Đà Điểu Emu", "name_en": "Emu", "stat": "45 kg"},
            {"rank": 4, "name_vi": "Chim Đầu Mào Phương Nam", "name_en": "Southern cassowary", "stat": "44 kg"},
            {"rank": 5, "name_vi": "Đại Bàng Biển Steller", "name_en": "Steller's sea eagle", "stat": "9 kg"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_famous_carnivorous_plants",
        "subject_vi": "Top 5 loài cây ăn thịt nổi bật",
        "subject_en": "Top 5 famous carnivorous plants",
        "comparison_angle": "special ability",
        "items": [
            {
                "rank": 1,
                "name_vi": "Cây Bắt Ruồi Venus",
                "name_en": "Venus flytrap",
                "stat": "Bẫy kẹp",
                "detail_vi": "khép lá cực nhanh khi lông cảm ứng bị chạm hai lần",
            },
            {
                "rank": 2,
                "name_vi": "Cây Nắp Ấm",
                "name_en": "Pitcher plant",
                "stat": "Bẫy hố",
                "detail_vi": "dụ côn trùng trượt xuống bình chứa dịch tiêu hóa",
            },
            {
                "rank": 3,
                "name_vi": "Gọng Vó",
                "name_en": "Sundew",
                "stat": "Lá dính",
                "detail_vi": "giọt keo trên lá giữ con mồi rồi cuộn lại tiêu hóa",
            },
            {
                "rank": 4,
                "name_vi": "Bèo Bắt Mồi",
                "name_en": "Bladderwort",
                "stat": "Bẫy hút",
                "detail_vi": "túi bẫy hút sinh vật nhỏ trong nước chỉ trong chớp mắt",
            },
            {
                "rank": 5,
                "name_vi": "Cây Bơ Hồng",
                "name_en": "Butterwort",
                "stat": "Lá nhớt",
                "detail_vi": "lá phủ chất nhầy giữ côn trùng nhỏ làm nguồn dinh dưỡng",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_strongest_bite_animals",
        "subject_vi": "Top 5 loài vật có lực cắn đáng sợ",
        "subject_en": "Top 5 animals with terrifying bite force",
        "comparison_angle": "bite force",
        "items": [
            {"rank": 1, "name_vi": "Cá Sấu Nước Mặn", "name_en": "Saltwater crocodile", "stat": "3700 PSI"},
            {"rank": 2, "name_vi": "Cá Sấu Sông Nile", "name_en": "Nile crocodile", "stat": "3000 PSI"},
            {"rank": 3, "name_vi": "Hà Mã", "name_en": "Hippopotamus", "stat": "1800 PSI"},
            {"rank": 4, "name_vi": "Báo Đốm Mỹ", "name_en": "Jaguar", "stat": "1500 PSI"},
            {"rank": 5, "name_vi": "Khỉ Đột", "name_en": "Gorilla", "stat": "1300 PSI"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_most_venomous_animals",
        "subject_vi": "Top 5 loài có nọc độc khiến ai cũng tò mò",
        "subject_en": "Top 5 fascinating venomous animals",
        "comparison_angle": "venom",
        "items": [
            {"rank": 1, "name_vi": "Sứa Hộp", "name_en": "Box jellyfish", "stat": "Cực độc"},
            {"rank": 2, "name_vi": "Rắn Taipan Nội Địa", "name_en": "Inland taipan", "stat": "Nọc mạnh"},
            {"rank": 3, "name_vi": "Bạch Tuộc Đốm Xanh", "name_en": "Blue-ringed octopus", "stat": "Tê liệt"},
            {"rank": 4, "name_vi": "Ốc Cối", "name_en": "Cone snail", "stat": "Phóng lao"},
            {"rank": 5, "name_vi": "Cá Đá", "name_en": "Stonefish", "stat": "Gai độc"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_longest_lived_animals",
        "subject_vi": "Top 5 loài vật sống lâu đến khó tin",
        "subject_en": "Top 5 incredibly long-lived animals",
        "comparison_angle": "lifespan",
        "items": [
            {"rank": 1, "name_vi": "Sò Đại Dương Quahog", "name_en": "Ocean quahog", "stat": "500 năm"},
            {"rank": 2, "name_vi": "Cá Mập Greenland", "name_en": "Greenland shark", "stat": "400 năm"},
            {"rank": 3, "name_vi": "Cá Voi Đầu Cong", "name_en": "Bowhead whale", "stat": "200 năm"},
            {"rank": 4, "name_vi": "Rùa Khổng Lồ", "name_en": "Giant tortoise", "stat": "150 năm"},
            {"rank": 5, "name_vi": "Nhím Biển Đỏ", "name_en": "Red sea urchin", "stat": "100 năm"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_camouflage_masters",
        "subject_vi": "Top 5 bậc thầy ngụy trang trong tự nhiên",
        "subject_en": "Top 5 camouflage masters in nature",
        "comparison_angle": "camouflage",
        "items": [
            {"rank": 1, "name_vi": "Bạch Tuộc Bắt Chước", "name_en": "Mimic octopus", "stat": "Đổi dáng"},
            {"rank": 2, "name_vi": "Mực Nang", "name_en": "Cuttlefish", "stat": "Đổi màu"},
            {"rank": 3, "name_vi": "Tắc Kè Đuôi Lá", "name_en": "Leaf-tailed gecko", "stat": "Giống lá"},
            {"rank": 4, "name_vi": "Bọ Que", "name_en": "Stick insect", "stat": "Giống cành"},
            {"rank": 5, "name_vi": "Cá Đá", "name_en": "Stonefish", "stat": "Giống đá"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_glowing_animals",
        "subject_vi": "Top 5 loài phát sáng đẹp như phim viễn tưởng",
        "subject_en": "Top 5 glowing animals that look unreal",
        "comparison_angle": "bioluminescence",
        "items": [
            {"rank": 1, "name_vi": "Đom Đóm", "name_en": "Firefly", "stat": "Tín hiệu sáng"},
            {"rank": 2, "name_vi": "Cá Cần Câu", "name_en": "Anglerfish", "stat": "Mồi phát sáng"},
            {"rank": 3, "name_vi": "Giun Phát Sáng", "name_en": "Glowworm", "stat": "Hang sao"},
            {"rank": 4, "name_vi": "Sứa Lược", "name_en": "Comb jelly", "stat": "Sắc cầu vồng"},
            {"rank": 5, "name_vi": "Bọ Cạp", "name_en": "Scorpion", "stat": "Huỳnh quang"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_fastest_sea_animals",
        "subject_vi": "Top 5 sinh vật biển lao nhanh nhất",
        "subject_en": "Top 5 fastest sea animals",
        "comparison_angle": "speed",
        "items": [
            {"rank": 1, "name_vi": "Cá Cờ", "name_en": "Sailfish", "stat": "110 km/h"},
            {"rank": 2, "name_vi": "Cá Kiếm", "name_en": "Swordfish", "stat": "97 km/h"},
            {"rank": 3, "name_vi": "Cá Marlin Đen", "name_en": "Black marlin", "stat": "82 km/h"},
            {"rank": 4, "name_vi": "Cá Ngừ Vây Vàng", "name_en": "Yellowfin tuna", "stat": "75 km/h"},
            {"rank": 5, "name_vi": "Cá Heo Thường", "name_en": "Common dolphin", "stat": "60 km/h"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_weirdest_plants",
        "subject_vi": "Top 5 loài cây kỳ lạ nhất hành tinh",
        "subject_en": "Top 5 weirdest plants on Earth",
        "comparison_angle": "special ability",
        "items": [
            {
                "rank": 1,
                "name_vi": "Hoa Xác Thối",
                "name_en": "Corpse flower",
                "stat": "Mùi xác",
                "detail_vi": "tỏa mùi thịt thối để dụ ruồi và bọ đến thụ phấn",
            },
            {
                "rank": 2,
                "name_vi": "Hoa Rafflesia",
                "name_en": "Rafflesia flower",
                "stat": "Hoa khổng lồ",
                "detail_vi": "bông hoa ký sinh cực lớn, có thể rộng gần một mét",
            },
            {
                "rank": 3,
                "name_vi": "Cây Máu Rồng",
                "name_en": "Dragon blood tree",
                "stat": "Nhựa đỏ",
                "detail_vi": "nhựa đỏ như máu chảy ra khi thân cây bị tổn thương",
            },
            {
                "rank": 4,
                "name_vi": "Cây Trinh Nữ",
                "name_en": "Sensitive plant",
                "stat": "Cụp lá",
                "detail_vi": "lá cụp lại rất nhanh khi bị chạm hoặc rung động",
            },
            {
                "rank": 5,
                "name_vi": "Cây Welwitschia",
                "name_en": "Welwitschia",
                "stat": "Sống lâu",
                "detail_vi": "hai lá lớn tiếp tục mọc trong điều kiện sa mạc khắc nghiệt",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_dangerous_plants",
        "subject_vi": "Top 5 loài cây nguy hiểm hơn vẻ ngoài",
        "subject_en": "Top 5 dangerous plants that look harmless",
        "comparison_angle": "toxicity",
        "items": [
            {
                "rank": 1,
                "name_vi": "Cây Thầu Dầu",
                "name_en": "Castor bean plant",
                "stat": "Ricin",
                "detail_vi": "hạt chứa ricin, chất độc có thể ức chế tế bào tạo protein",
            },
            {
                "rank": 2,
                "name_vi": "Cây Phụ Tử",
                "name_en": "Monkshood",
                "stat": "Aconitine",
                "detail_vi": "aconitine tác động lên kênh natri, dễ gây rối loạn nhịp tim",
            },
            {
                "rank": 3,
                "name_vi": "Trúc Đào",
                "name_en": "Oleander",
                "stat": "Độc tim",
                "detail_vi": "glycoside tim có thể làm rối loạn nhịp và co bóp tim",
            },
            {
                "rank": 4,
                "name_vi": "Cây Cà Độc Dược",
                "name_en": "Jimsonweed",
                "stat": "Gây ảo giác",
                "detail_vi": "alkaloid tropane có thể gây mê sảng, ảo giác và tim đập nhanh",
            },
            {
                "rank": 5,
                "name_vi": "Cây Manchineel",
                "name_en": "Manchineel tree",
                "stat": "Nhựa độc",
                "detail_vi": "nhựa cây gây bỏng rát da, quả và khói đốt cũng nguy hiểm",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_animal_architects",
        "subject_vi": "Top 5 kiến trúc sư siêu đẳng trong tự nhiên",
        "subject_en": "Top 5 animal architects in nature",
        "comparison_angle": "building ability",
        "items": [
            {
                "rank": 1,
                "name_vi": "Hải Ly",
                "name_en": "Beaver",
                "stat": "Đập nước",
                "detail_vi": "chặt cây, xếp cành và bùn để đổi dòng chảy",
            },
            {
                "rank": 2,
                "name_vi": "Mối",
                "name_en": "Termite",
                "stat": "Tháp đất",
                "detail_vi": "xây tháp có hệ thống thông gió tự nhiên rất ổn định",
            },
            {
                "rank": 3,
                "name_vi": "Chim Sẻ Dòng Dọc",
                "name_en": "Weaverbird",
                "stat": "Tổ dệt",
                "detail_vi": "đan cỏ thành tổ treo chắc chắn để thu hút bạn tình",
            },
            {
                "rank": 4,
                "name_vi": "Ong Mật",
                "name_en": "Honeybee",
                "stat": "Tổ lục giác",
                "detail_vi": "xây ô sáp lục giác để tiết kiệm vật liệu và diện tích",
            },
            {
                "rank": 5,
                "name_vi": "Kiến Cắt Lá",
                "name_en": "Leafcutter ant",
                "stat": "Trang trại nấm",
                "detail_vi": "cắt lá mang về tổ để nuôi nấm làm thức ăn",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_animal_super_senses",
        "subject_vi": "Top 5 siêu giác quan khiến con người phải ghen tị",
        "subject_en": "Top 5 animal super senses",
        "comparison_angle": "special ability",
        "items": [
            {
                "rank": 1,
                "name_vi": "Cá Mập",
                "name_en": "Shark",
                "stat": "Cảm điện",
                "detail_vi": "cảm nhận tín hiệu điện rất yếu từ cơ thể con mồi",
            },
            {
                "rank": 2,
                "name_vi": "Dơi",
                "name_en": "Bat",
                "stat": "Định vị âm",
                "detail_vi": "phát sóng siêu âm rồi nghe tiếng vọng để bay trong tối",
            },
            {
                "rank": 3,
                "name_vi": "Rắn Hổ Lục",
                "name_en": "Pit viper",
                "stat": "Cảm nhiệt",
                "detail_vi": "hố cảm nhiệt giúp phát hiện con mồi máu nóng trong bóng tối",
            },
            {
                "rank": 4,
                "name_vi": "Đại Bàng",
                "name_en": "Eagle",
                "stat": "Mắt siêu xa",
                "detail_vi": "thị lực sắc bén giúp phát hiện con mồi từ khoảng cách xa",
            },
            {
                "rank": 5,
                "name_vi": "Chó",
                "name_en": "Dog",
                "stat": "Khứu giác mạnh",
                "detail_vi": "mũi có hàng trăm triệu thụ thể mùi để lần theo dấu vết",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_extreme_survivors",
        "subject_vi": "Top 5 sinh vật sống sót ở nơi khắc nghiệt",
        "subject_en": "Top 5 extreme survivors in nature",
        "comparison_angle": "survival",
        "items": [
            {"rank": 1, "name_vi": "Gấu Nước", "name_en": "Tardigrade", "stat": "Cực hạn"},
            {"rank": 2, "name_vi": "Vi Khuẩn Deinococcus", "name_en": "Deinococcus radiodurans", "stat": "Chịu bức xạ"},
            {"rank": 3, "name_vi": "Lạc Đà Một Bướu", "name_en": "Dromedary camel", "stat": "Chịu khát"},
            {"rank": 4, "name_vi": "Cá Phổi", "name_en": "Lungfish", "stat": "Ngủ bùn"},
            {"rank": 5, "name_vi": "Chim Cánh Cụt Hoàng Đế", "name_en": "Emperor penguin", "stat": "Băng giá"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_surprising_parenting_animals",
        "subject_vi": "Top 5 ông bố bà mẹ tận tụy trong thế giới động vật",
        "subject_en": "Top 5 surprising animal parents",
        "comparison_angle": "parenting",
        "items": [
            {
                "rank": 1,
                "name_vi": "Chim Cánh Cụt Hoàng Đế",
                "name_en": "Emperor penguin",
                "stat": "Ấp trứng",
                "detail_vi": "con đực giữ trứng trên chân qua mùa đông băng giá",
            },
            {
                "rank": 2,
                "name_vi": "Cá Ngựa",
                "name_en": "Seahorse",
                "stat": "Con đực mang thai",
                "detail_vi": "con cái gửi trứng vào túi ấp của con đực",
            },
            {
                "rank": 3,
                "name_vi": "Cá Sấu",
                "name_en": "Crocodile",
                "stat": "Bảo vệ con",
                "detail_vi": "mẹ cá sấu ngậm con rất nhẹ để đưa xuống nước",
            },
            {
                "rank": 4,
                "name_vi": "Ếch Phi Tiêu Độc",
                "name_en": "Poison dart frog",
                "stat": "Cõng nòng nọc",
                "detail_vi": "bố mẹ chở nòng nọc tới vũng nước nhỏ an toàn",
            },
            {
                "rank": 5,
                "name_vi": "Voi",
                "name_en": "Elephant",
                "stat": "Cả đàn chăm",
                "detail_vi": "voi con được mẹ, dì và cả đàn cùng bảo vệ",
            },
        ],
    },
]

SINGLE_TOPICS = [
    {
        "topic_type": "single_card",
        "topic_key": "cheetah_speed_card",
        "subject_vi": "Báo Săn",
        "subject_en": "Cheetah",
        "fact_label": "speed",
        "fact_value": "110 km/h",
        "fact_detail": "one of the fastest land animals on Earth",
        "detail_vi": "có thể bứt tốc cực nhanh trong vài giây ngắn",
    },
    {
        "topic_type": "single_card",
        "topic_key": "mantis_shrimp_punch_card",
        "subject_vi": "Tôm Tít",
        "subject_en": "Mantis shrimp",
        "fact_label": "special ability",
        "fact_value": "cú đấm siêu tốc",
        "fact_detail": "its strike is among the fastest animal movements and can crack shells",
        "detail_vi": "cú đấm tạo lực mạnh đến mức có thể làm nứt vỏ con mồi",
    },
    {
        "topic_type": "single_card",
        "topic_key": "electric_eel_shock_card",
        "subject_vi": "Lươn Điện",
        "subject_en": "Electric eel",
        "fact_label": "special ability",
        "fact_value": "phóng điện mạnh",
        "fact_detail": "it can generate powerful electric pulses to hunt and defend itself",
        "detail_vi": "dùng xung điện mạnh để săn mồi và tự vệ dưới nước",
    },
    {
        "topic_type": "single_card",
        "topic_key": "immortal_jellyfish_card",
        "subject_vi": "Sứa Bất Tử",
        "subject_en": "Immortal jellyfish",
        "fact_label": "special ability",
        "fact_value": "đảo ngược tuổi",
        "fact_detail": "it can revert to an earlier life stage under stress",
        "detail_vi": "khi gặp căng thẳng, nó có thể quay về giai đoạn non hơn",
    },
    {
        "topic_type": "single_card",
        "topic_key": "axolotl_regeneration_card",
        "subject_vi": "Kỳ Giông Mexico",
        "subject_en": "Axolotl",
        "fact_label": "regeneration",
        "fact_value": "tái tạo chi",
        "fact_detail": "it can regrow limbs and repair parts of its body with unusual ability",
        "detail_vi": "có thể mọc lại chi và sửa chữa một số mô bị tổn thương",
    },
    {
        "topic_type": "single_card",
        "topic_key": "archerfish_water_shot_card",
        "subject_vi": "Cá Mang Rổ",
        "subject_en": "Archerfish",
        "fact_label": "hunting ability",
        "fact_value": "bắn tia nước",
        "fact_detail": "it shoots water jets to knock insects off branches above the surface",
        "detail_vi": "bắn tia nước chính xác để hạ côn trùng trên cành cây",
    },
    {
        "topic_type": "single_card",
        "topic_key": "mimic_octopus_card",
        "subject_vi": "Bạch Tuộc Bắt Chước",
        "subject_en": "Mimic octopus",
        "fact_label": "camouflage",
        "fact_value": "giả dạng bậc thầy",
        "fact_detail": "it can imitate the look and movement of several dangerous sea animals",
        "detail_vi": "bắt chước hình dáng và cách di chuyển của loài biển nguy hiểm",
    },
    {
        "topic_type": "single_card",
        "topic_key": "lyrebird_voice_card",
        "subject_vi": "Chim Lia",
        "subject_en": "Lyrebird",
        "fact_label": "sound mimicry",
        "fact_value": "nhại âm siêu thật",
        "fact_detail": "it is famous for copying natural and artificial sounds with striking accuracy",
        "detail_vi": "có thể bắt chước nhiều âm thanh tự nhiên và nhân tạo rất giống",
    },
    {
        "topic_type": "single_card",
        "topic_key": "pangolin_armor_card",
        "subject_vi": "Tê Tê",
        "subject_en": "Pangolin",
        "fact_label": "defense",
        "fact_value": "áo giáp vảy",
        "fact_detail": "its keratin scales help it curl into a tough defensive ball",
        "detail_vi": "cuộn tròn thành quả bóng vảy cứng để tự bảo vệ",
    },
    {
        "topic_type": "single_card",
        "topic_key": "tardigrade_survival_card",
        "subject_vi": "Gấu Nước",
        "subject_en": "Tardigrade",
        "fact_label": "survival",
        "fact_value": "sống cực hạn",
        "fact_detail": "it can survive extreme environments by entering a dormant state",
        "detail_vi": "chuyển sang trạng thái ngủ sâu để chịu điều kiện khắc nghiệt",
    },
    {
        "topic_type": "single_card",
        "topic_key": "corpse_flower_card",
        "subject_vi": "Hoa Xác Thối",
        "subject_en": "Corpse flower",
        "fact_label": "plant ability",
        "fact_value": "mùi xác thối",
        "fact_detail": "its odor attracts pollinators that are drawn to decaying organic matter",
        "detail_vi": "tỏa mùi giống xác thối để thu hút côn trùng thụ phấn",
    },
    {
        "topic_type": "single_card",
        "topic_key": "rafflesia_giant_flower_card",
        "subject_vi": "Hoa Rafflesia",
        "subject_en": "Rafflesia flower",
        "fact_label": "plant record",
        "fact_value": "hoa khổng lồ",
        "fact_detail": "it produces one of the largest individual flowers in the world",
        "detail_vi": "tạo ra một trong những bông hoa đơn lẻ lớn nhất thế giới",
    },
    {
        "topic_type": "single_card",
        "topic_key": "dragon_blood_tree_card",
        "subject_vi": "Cây Máu Rồng",
        "subject_en": "Dragon blood tree",
        "fact_label": "plant feature",
        "fact_value": "nhựa đỏ",
        "fact_detail": "its red resin gives the tree its dramatic name and unusual appearance",
        "detail_vi": "nhựa cây màu đỏ khiến nó có vẻ ngoài rất kỳ lạ",
    },
    {
        "topic_type": "single_card",
        "topic_key": "owl_silent_flight_card",
        "subject_vi": "Cú Mèo",
        "subject_en": "Owl",
        "fact_label": "special ability",
        "fact_value": "bay gần như im lặng",
        "fact_detail": "its wing structure helps reduce turbulence and noise",
        "detail_vi": "cấu trúc lông cánh giúp giảm tiếng động khi lao xuống săn mồi",
    },
    {
        "topic_type": "single_card",
        "topic_key": "exploding_ant_defense_card",
        "subject_vi": "Kiến Nổ",
        "subject_en": "Exploding ant",
        "fact_label": "defense",
        "fact_value": "tự nổ bảo vệ đàn",
        "fact_detail": "some worker ants rupture their own bodies to release sticky defensive fluid",
        "detail_vi": "một số kiến thợ hy sinh thân mình để phun chất dính bảo vệ tổ",
    },
    {
        "topic_type": "single_card",
        "topic_key": "venus_flytrap_card",
        "subject_vi": "Cây Bắt Ruồi Venus",
        "subject_en": "Venus flytrap",
        "fact_label": "special ability",
        "fact_value": "cây ăn thịt",
        "fact_detail": "it traps insects with a fast snap-trap mechanism",
        "detail_vi": "khép bẫy rất nhanh để giữ côn trùng làm nguồn dinh dưỡng",
    },
]


MATCHUP_TOPICS = [
    {
        "topic_type": "matchup_versus",
        "topic_key": "tibetan_mastiff_vs_caucasian_shepherd",
        "subject_vi": "Chó Ngao Tây Tạng so tài Chó Chăn Cừu Kavkaz",
        "subject_en": "Tibetan Mastiff versus Caucasian Shepherd",
        "left": {
            "name_vi": "Chó Ngao Tây Tạng",
            "name_en": "Tibetan Mastiff",
            "height": "76 cm",
            "weight": "70 kg",
            "bite_force": "Lực hàm mạnh",
            "edge_vi": "lông cổ dày, tiếng sủa uy hiếp, bản năng canh gác",
        },
        "right": {
            "name_vi": "Chó Chăn Cừu Kavkaz",
            "name_en": "Caucasian Shepherd",
            "height": "75 cm",
            "weight": "75 kg",
            "bite_force": "Lực hàm mạnh",
            "edge_vi": "thân dày, gan lì, phản xạ bảo vệ lãnh thổ",
        },
        "verdict_vi": "Hai giống chó khá ngang thể hình; khác biệt nằm ở lối canh gác, độ lì và phản xạ bảo vệ.",
        "reality_note_vi": "Đây là so sánh kiến thức về giống chó, không cổ vũ cho chó đối đầu thật.",
        "debate_question_vi": "Bạn chọn vẻ uy nghi của Ngao Tây Tạng hay độ lì của Kavkaz?",
    },
    {
        "topic_type": "matchup_versus",
        "topic_key": "dingo_vs_coyote",
        "subject_vi": "Chó Dingo so tài Sói Đồng Cỏ",
        "subject_en": "Dingo versus coyote",
        "left": {
            "name_vi": "Chó Dingo",
            "name_en": "Dingo",
            "height": "60 cm",
            "weight": "18 kg",
            "bite_force": "Sức bền tốt",
            "edge_vi": "săn mồi linh hoạt, chịu nóng tốt, di chuyển bền bỉ",
        },
        "right": {
            "name_vi": "Sói Đồng Cỏ",
            "name_en": "Coyote",
            "height": "60 cm",
            "weight": "18 kg",
            "bite_force": "Nhanh nhẹn",
            "edge_vi": "linh hoạt, thích nghi tốt, di chuyển khéo trong địa hình mở",
        },
        "verdict_vi": "Dingo và sói đồng cỏ khá ngang tầm; dingo nhỉnh ở sức bền, coyote nổi bật ở độ lanh lợi.",
        "reality_note_vi": "Đây là so sánh đặc điểm giữa hai loài canid cỡ trung, không cổ vũ đối đầu thật.",
        "debate_question_vi": "Bạn chọn sức bền của dingo hay sự khôn lanh của sói đồng cỏ?",
    },
    {
        "topic_type": "matchup_versus",
        "topic_key": "jaguar_vs_leopard",
        "subject_vi": "Báo Đốm Mỹ so tài Báo Hoa Mai",
        "subject_en": "Jaguar versus leopard",
        "left": {
            "name_vi": "Báo Đốm Mỹ",
            "name_en": "Jaguar",
            "height": "75 cm",
            "weight": "90 kg",
            "bite_force": "Cắn xuyên sọ",
            "edge_vi": "hàm cực khỏe, thân chắc, giỏi phục kích gần nước",
        },
        "right": {
            "name_vi": "Báo Hoa Mai",
            "name_en": "Leopard",
            "height": "70 cm",
            "weight": "70 kg",
            "bite_force": "Leo cây giỏi",
            "edge_vi": "nhẹ hơn, cực linh hoạt, kéo mồi lên cây rất khỏe",
        },
        "verdict_vi": "Báo đốm Mỹ lợi thế về lực hàm, còn báo hoa mai nổi bật ở độ linh hoạt và kỹ năng leo cây.",
        "reality_note_vi": "Đây là so sánh đặc điểm sinh học giữa hai loài mèo lớn, không cổ vũ đối đầu thật.",
        "debate_question_vi": "Bạn chọn lực hàm của báo đốm hay độ khéo của báo hoa mai?",
    },
    {
        "topic_type": "matchup_versus",
        "topic_key": "great_white_shark_vs_tiger_shark",
        "subject_vi": "Cá Mập Trắng so tài Cá Mập Hổ",
        "subject_en": "Great white shark versus tiger shark",
        "left": {
            "name_vi": "Cá Mập Trắng",
            "name_en": "Great white shark",
            "height": "Dài 4.5 m",
            "weight": "900 kg",
            "bite_force": "Cú cắn mạnh",
            "edge_vi": "tốc độ bứt phá, lực cắn lớn, săn mồi bằng cú lao nhanh",
        },
        "right": {
            "name_vi": "Cá Mập Hổ",
            "name_en": "Tiger shark",
            "height": "Dài 4 m",
            "weight": "850 kg",
            "bite_force": "Ăn tạp khỏe",
            "edge_vi": "hàm răng cưa, ăn đa dạng, cực lì trong môi trường biển",
        },
        "verdict_vi": "Cá mập trắng nổi bật ở cú lao săn mồi, còn cá mập hổ đáng nể vì độ lì và khẩu phần cực rộng.",
        "reality_note_vi": "Đây là so sánh đặc điểm sinh học giữa hai loài cá mập lớn, không cổ vũ đối đầu thật.",
        "debate_question_vi": "Bạn thấy cú lao của cá mập trắng hay độ lì của cá mập hổ đáng sợ hơn?",
    },
]


def get_topic_by_index(index: int) -> dict:
    """Rotate evenly across Top 5, single-card, and matchup topics."""
    topic_group = index % 3
    group_index = index // 3

    if topic_group == 0:
        comparison_slot_index = group_index
        if comparison_slot_index < len(COMPARISON_TOPICS):
            return deepcopy(COMPARISON_TOPICS[comparison_slot_index])

        from app.generated_topic_service import get_generated_topic

        generated_index = comparison_slot_index - len(COMPARISON_TOPICS)
        return get_generated_topic(
            "comparison_top5",
            generated_index,
            COMPARISON_TOPICS + SINGLE_TOPICS + MATCHUP_TOPICS,
        )

    if topic_group == 1:
        single_slot_index = group_index
        if single_slot_index < len(SINGLE_TOPICS):
            return deepcopy(SINGLE_TOPICS[single_slot_index])

        from app.generated_topic_service import get_generated_topic

        generated_index = single_slot_index - len(SINGLE_TOPICS)
        return get_generated_topic(
            "single_card",
            generated_index,
            COMPARISON_TOPICS + SINGLE_TOPICS + MATCHUP_TOPICS,
        )

    matchup_slot_index = group_index
    if matchup_slot_index < len(MATCHUP_TOPICS):
        return deepcopy(MATCHUP_TOPICS[matchup_slot_index])

    from app.generated_topic_service import get_generated_topic

    generated_index = matchup_slot_index - len(MATCHUP_TOPICS)
    return get_generated_topic(
        "matchup_versus",
        generated_index,
        COMPARISON_TOPICS + SINGLE_TOPICS + MATCHUP_TOPICS,
    )
