from copy import deepcopy


COMPARISON_TOPICS = [
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_fastest_land_animals",
        "subject_vi": "Top 5 con vật chạy nhanh nhất trên cạn",
        "subject_en": "Top 5 fastest land animals",
        "comparison_angle": "speed",
        "items": [
            {"rank": 1, "name_vi": "Báo Săn", "name_en": "Cheetah", "stat": "110 km/h"},
            {"rank": 2, "name_vi": "Linh Dương Sừng Nhánh", "name_en": "Pronghorn", "stat": "88 km/h"},
            {"rank": 3, "name_vi": "Linh Dương Springbok", "name_en": "Springbok", "stat": "88 km/h"},
            {"rank": 4, "name_vi": "Linh Dương Đầu Bò Xanh", "name_en": "Blue wildebeest", "stat": "80 km/h"},
            {"rank": 5, "name_vi": "Sư Tử", "name_en": "Lion", "stat": "80 km/h"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_tallest_land_animals",
        "subject_vi": "Top 5 loài động vật cao nhất trên cạn",
        "subject_en": "Top 5 tallest land animals",
        "comparison_angle": "height",
        "items": [
            {"rank": 1, "name_vi": "Hươu Cao Cổ", "name_en": "Giraffe", "stat": "5.5 m"},
            {"rank": 2, "name_vi": "Voi Châu Phi", "name_en": "African elephant", "stat": "4.0 m"},
            {"rank": 3, "name_vi": "Lạc Đà Một Bướu", "name_en": "Dromedary camel", "stat": "2.3 m"},
            {"rank": 4, "name_vi": "Nai Sừng Tấm", "name_en": "Moose", "stat": "2.1 m"},
            {"rank": 5, "name_vi": "Ngựa Shire", "name_en": "Shire horse", "stat": "2.0 m"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_heaviest_land_animals",
        "subject_vi": "Top 5 động vật trên cạn nặng nhất",
        "subject_en": "Top 5 heaviest land animals",
        "comparison_angle": "weight",
        "items": [
            {"rank": 1, "name_vi": "Voi Châu Phi", "name_en": "African elephant", "stat": "6000 kg"},
            {"rank": 2, "name_vi": "Voi Châu Á", "name_en": "Asian elephant", "stat": "5000 kg"},
            {"rank": 3, "name_vi": "Tê Giác Trắng", "name_en": "White rhinoceros", "stat": "2300 kg"},
            {"rank": 4, "name_vi": "Hà Mã", "name_en": "Hippopotamus", "stat": "1800 kg"},
            {"rank": 5, "name_vi": "Hươu Cao Cổ", "name_en": "Giraffe", "stat": "1200 kg"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_biggest_birds",
        "subject_vi": "Top 5 loài chim lớn nhất thế giới",
        "subject_en": "Top 5 biggest birds in the world",
        "comparison_angle": "size",
        "items": [
            {"rank": 1, "name_vi": "Đà Điểu Châu Phi", "name_en": "Ostrich", "stat": "156 kg"},
            {"rank": 2, "name_vi": "Đà Điểu Somali", "name_en": "Somali ostrich", "stat": "130 kg"},
            {"rank": 3, "name_vi": "Đà Điểu Emu", "name_en": "Emu", "stat": "45 kg"},
            {"rank": 4, "name_vi": "Chim Đầu Mào Phương Nam", "name_en": "Southern cassowary", "stat": "44 kg"},
            {"rank": 5, "name_vi": "Đại Bàng Biển Steller", "name_en": "Steller's sea eagle", "stat": "9 kg"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_famous_carnivorous_plants",
        "subject_vi": "Top 5 loài cây ăn thịt nổi bật",
        "subject_en": "Top 5 famous carnivorous plants",
        "comparison_angle": "special ability",
        "items": [
            {
                "rank": 1,
                "name_vi": "Cây Bắt Ruồi Venus",
                "name_en": "Venus flytrap",
                "stat": "Bẫy kẹp",
                "detail_vi": "khép lá cực nhanh khi lông cảm ứng bị chạm hai lần",
            },
            {
                "rank": 2,
                "name_vi": "Cây Nắp Ấm",
                "name_en": "Pitcher plant",
                "stat": "Bẫy hố",
                "detail_vi": "dụ côn trùng trượt xuống bình chứa dịch tiêu hóa",
            },
            {
                "rank": 3,
                "name_vi": "Gọng Vó",
                "name_en": "Sundew",
                "stat": "Lá dính",
                "detail_vi": "giọt keo trên lá giữ con mồi rồi cuộn lại tiêu hóa",
            },
            {
                "rank": 4,
                "name_vi": "Bèo Bắt Mồi",
                "name_en": "Bladderwort",
                "stat": "Bẫy hút",
                "detail_vi": "túi bẫy hút sinh vật nhỏ trong nước chỉ trong chớp mắt",
            },
            {
                "rank": 5,
                "name_vi": "Cây Bơ Hồng",
                "name_en": "Butterwort",
                "stat": "Lá nhớt",
                "detail_vi": "lá phủ chất nhầy giữ côn trùng nhỏ làm nguồn dinh dưỡng",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_strongest_bite_animals",
        "subject_vi": "Top 5 loài vật có lực cắn đáng sợ",
        "subject_en": "Top 5 animals with terrifying bite force",
        "comparison_angle": "bite force",
        "items": [
            {"rank": 1, "name_vi": "Cá Sấu Nước Mặn", "name_en": "Saltwater crocodile", "stat": "3700 PSI"},
            {"rank": 2, "name_vi": "Cá Sấu Sông Nile", "name_en": "Nile crocodile", "stat": "3000 PSI"},
            {"rank": 3, "name_vi": "Hà Mã", "name_en": "Hippopotamus", "stat": "1800 PSI"},
            {"rank": 4, "name_vi": "Báo Đốm Mỹ", "name_en": "Jaguar", "stat": "1500 PSI"},
            {"rank": 5, "name_vi": "Khỉ Đột", "name_en": "Gorilla", "stat": "1300 PSI"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_most_venomous_animals",
        "subject_vi": "Top 5 loài có nọc độc khiến ai cũng tò mò",
        "subject_en": "Top 5 fascinating venomous animals",
        "comparison_angle": "venom",
        "items": [
            {"rank": 1, "name_vi": "Sứa Hộp", "name_en": "Box jellyfish", "stat": "Cực độc"},
            {"rank": 2, "name_vi": "Rắn Taipan Nội Địa", "name_en": "Inland taipan", "stat": "Nọc mạnh"},
            {"rank": 3, "name_vi": "Bạch Tuộc Đốm Xanh", "name_en": "Blue-ringed octopus", "stat": "Tê liệt"},
            {"rank": 4, "name_vi": "Ốc Cối", "name_en": "Cone snail", "stat": "Phóng lao"},
            {"rank": 5, "name_vi": "Cá Đá", "name_en": "Stonefish", "stat": "Gai độc"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_longest_lived_animals",
        "subject_vi": "Top 5 loài vật sống lâu đến khó tin",
        "subject_en": "Top 5 incredibly long-lived animals",
        "comparison_angle": "lifespan",
        "items": [
            {"rank": 1, "name_vi": "Sò Đại Dương Quahog", "name_en": "Ocean quahog", "stat": "500 năm"},
            {"rank": 2, "name_vi": "Cá Mập Greenland", "name_en": "Greenland shark", "stat": "400 năm"},
            {"rank": 3, "name_vi": "Cá Voi Đầu Cong", "name_en": "Bowhead whale", "stat": "200 năm"},
            {"rank": 4, "name_vi": "Rùa Khổng Lồ", "name_en": "Giant tortoise", "stat": "150 năm"},
            {"rank": 5, "name_vi": "Nhím Biển Đỏ", "name_en": "Red sea urchin", "stat": "100 năm"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_camouflage_masters",
        "subject_vi": "Top 5 bậc thầy ngụy trang trong tự nhiên",
        "subject_en": "Top 5 camouflage masters in nature",
        "comparison_angle": "camouflage",
        "items": [
            {"rank": 1, "name_vi": "Bạch Tuộc Bắt Chước", "name_en": "Mimic octopus", "stat": "Đổi dáng"},
            {"rank": 2, "name_vi": "Mực Nang", "name_en": "Cuttlefish", "stat": "Đổi màu"},
            {"rank": 3, "name_vi": "Tắc Kè Đuôi Lá", "name_en": "Leaf-tailed gecko", "stat": "Giống lá"},
            {"rank": 4, "name_vi": "Bọ Que", "name_en": "Stick insect", "stat": "Giống cành"},
            {"rank": 5, "name_vi": "Cá Đá", "name_en": "Stonefish", "stat": "Giống đá"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_glowing_animals",
        "subject_vi": "Top 5 loài phát sáng đẹp như phim viễn tưởng",
        "subject_en": "Top 5 glowing animals that look unreal",
        "comparison_angle": "bioluminescence",
        "items": [
            {"rank": 1, "name_vi": "Đom Đóm", "name_en": "Firefly", "stat": "Tín hiệu sáng"},
            {"rank": 2, "name_vi": "Cá Cần Câu", "name_en": "Anglerfish", "stat": "Mồi phát sáng"},
            {"rank": 3, "name_vi": "Giun Phát Sáng", "name_en": "Glowworm", "stat": "Hang sao"},
            {"rank": 4, "name_vi": "Sứa Lược", "name_en": "Comb jelly", "stat": "Sắc cầu vồng"},
            {"rank": 5, "name_vi": "Bọ Cạp", "name_en": "Scorpion", "stat": "Huỳnh quang"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_fastest_sea_animals",
        "subject_vi": "Top 5 sinh vật biển lao nhanh nhất",
        "subject_en": "Top 5 fastest sea animals",
        "comparison_angle": "speed",
        "items": [
            {"rank": 1, "name_vi": "Cá Cờ", "name_en": "Sailfish", "stat": "110 km/h"},
            {"rank": 2, "name_vi": "Cá Kiếm", "name_en": "Swordfish", "stat": "97 km/h"},
            {"rank": 3, "name_vi": "Cá Marlin Đen", "name_en": "Black marlin", "stat": "82 km/h"},
            {"rank": 4, "name_vi": "Cá Ngừ Vây Vàng", "name_en": "Yellowfin tuna", "stat": "75 km/h"},
            {"rank": 5, "name_vi": "Cá Heo Thường", "name_en": "Common dolphin", "stat": "60 km/h"},
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_weirdest_plants",
        "subject_vi": "Top 5 loài cây kỳ lạ nhất hành tinh",
        "subject_en": "Top 5 weirdest plants on Earth",
        "comparison_angle": "special ability",
        "items": [
            {
                "rank": 1,
                "name_vi": "Hoa Xác Thối",
                "name_en": "Corpse flower",
                "stat": "Mùi xác",
                "detail_vi": "tỏa mùi thịt thối để dụ ruồi và bọ đến thụ phấn",
            },
            {
                "rank": 2,
                "name_vi": "Hoa Rafflesia",
                "name_en": "Rafflesia flower",
                "stat": "Hoa khổng lồ",
                "detail_vi": "bông hoa ký sinh cực lớn, có thể rộng gần một mét",
            },
            {
                "rank": 3,
                "name_vi": "Cây Máu Rồng",
                "name_en": "Dragon blood tree",
                "stat": "Nhựa đỏ",
                "detail_vi": "nhựa đỏ như máu chảy ra khi thân cây bị tổn thương",
            },
            {
                "rank": 4,
                "name_vi": "Cây Trinh Nữ",
                "name_en": "Sensitive plant",
                "stat": "Cụp lá",
                "detail_vi": "lá cụp lại rất nhanh khi bị chạm hoặc rung động",
            },
            {
                "rank": 5,
                "name_vi": "Cây Welwitschia",
                "name_en": "Welwitschia",
                "stat": "Sống lâu",
                "detail_vi": "hai lá lớn tiếp tục mọc trong điều kiện sa mạc khắc nghiệt",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_dangerous_plants",
        "subject_vi": "Top 5 loài cây nguy hiểm hơn vẻ ngoài",
        "subject_en": "Top 5 dangerous plants that look harmless",
        "comparison_angle": "toxicity",
        "items": [
            {
                "rank": 1,
                "name_vi": "Cây Thầu Dầu",
                "name_en": "Castor bean plant",
                "stat": "Ricin",
                "detail_vi": "hạt chứa ricin, chất độc có thể ức chế tế bào tạo protein",
            },
            {
                "rank": 2,
                "name_vi": "Cây Phụ Tử",
                "name_en": "Monkshood",
                "stat": "Aconitine",
                "detail_vi": "aconitine tác động lên kênh natri, dễ gây rối loạn nhịp tim",
            },
            {
                "rank": 3,
                "name_vi": "Trúc Đào",
                "name_en": "Oleander",
                "stat": "Độc tim",
                "detail_vi": "glycoside tim có thể làm rối loạn nhịp và co bóp tim",
            },
            {
                "rank": 4,
                "name_vi": "Cây Cà Độc Dược",
                "name_en": "Jimsonweed",
                "stat": "Gây ảo giác",
                "detail_vi": "alkaloid tropane có thể gây mê sảng, ảo giác và tim đập nhanh",
            },
            {
                "rank": 5,
                "name_vi": "Cây Manchineel",
                "name_en": "Manchineel tree",
                "stat": "Nhựa độc",
                "detail_vi": "nhựa cây gây bỏng rát da, quả và khói đốt cũng nguy hiểm",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_animal_architects",
        "subject_vi": "Top 5 kiến trúc sư siêu đẳng trong tự nhiên",
        "subject_en": "Top 5 animal architects in nature",
        "comparison_angle": "building ability",
        "items": [
            {
                "rank": 1,
                "name_vi": "Hải Ly",
                "name_en": "Beaver",
                "stat": "Đập nước",
                "detail_vi": "chặt cây, xếp cành và bùn để đổi dòng chảy",
            },
            {
                "rank": 2,
                "name_vi": "Mối",
                "name_en": "Termite",
                "stat": "Tháp đất",
                "detail_vi": "xây tháp có hệ thống thông gió tự nhiên rất ổn định",
            },
            {
                "rank": 3,
                "name_vi": "Chim Sẻ Dòng Dọc",
                "name_en": "Weaverbird",
                "stat": "Tổ dệt",
                "detail_vi": "đan cỏ thành tổ treo chắc chắn để thu hút bạn tình",
            },
            {
                "rank": 4,
                "name_vi": "Ong Mật",
                "name_en": "Honeybee",
                "stat": "Tổ lục giác",
                "detail_vi": "xây ô sáp lục giác để tiết kiệm vật liệu và diện tích",
            },
            {
                "rank": 5,
                "name_vi": "Kiến Cắt Lá",
                "name_en": "Leafcutter ant",
                "stat": "Trang trại nấm",
                "detail_vi": "cắt lá mang về tổ để nuôi nấm làm thức ăn",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_animal_super_senses",
        "subject_vi": "Top 5 siêu giác quan khiến con người phải ghen tị",
        "subject_en": "Top 5 animal super senses",
        "comparison_angle": "special ability",
        "items": [
            {
                "rank": 1,
                "name_vi": "Cá Mập",
                "name_en": "Shark",
                "stat": "Cảm điện",
                "detail_vi": "cảm nhận tín hiệu điện rất yếu từ cơ thể con mồi",
            },
            {
                "rank": 2,
                "name_vi": "Dơi",
                "name_en": "Bat",
                "stat": "Định vị âm",
                "detail_vi": "phát sóng siêu âm rồi nghe tiếng vọng để bay trong tối",
            },
            {
                "rank": 3,
                "name_vi": "Rắn Hổ Lục",
                "name_en": "Pit viper",
                "stat": "Cảm nhiệt",
                "detail_vi": "hố cảm nhiệt giúp phát hiện con mồi máu nóng trong bóng tối",
            },
            {
                "rank": 4,
                "name_vi": "Đại Bàng",
                "name_en": "Eagle",
                "stat": "Mắt siêu xa",
                "detail_vi": "thị lực sắc bén giúp phát hiện con mồi từ khoảng cách xa",
            },
            {
                "rank": 5,
                "name_vi": "Chó",
                "name_en": "Dog",
                "stat": "Khứu giác mạnh",
                "detail_vi": "mũi có hàng trăm triệu thụ thể mùi để lần theo dấu vết",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_extreme_survivors",
        "subject_vi": "Top 5 sinh vật sống sót ở nơi khắc nghiệt",
        "subject_en": "Top 5 extreme survivors in nature",
        "comparison_angle": "survival",
        "items": [
            {
                "rank": 1,
                "name_vi": "Gấu Nước",
                "name_en": "Tardigrade",
                "stat": "Cực hạn",
                "detail_vi": "rút gần hết nước khỏi cơ thể rồi chuyển sang trạng thái ngủ",
            },
            {
                "rank": 2,
                "name_vi": "Vi Khuẩn Deinococcus",
                "name_en": "Deinococcus radiodurans",
                "stat": "Chịu bức xạ",
                "detail_vi": "sửa chữa ADN bị phá hỏng sau liều bức xạ rất cao",
            },
            {
                "rank": 3,
                "name_vi": "Lạc Đà Một Bướu",
                "name_en": "Dromedary camel",
                "stat": "Chịu khát",
                "detail_vi": "giữ nước cực tốt và chịu mất nước cơ thể lâu hơn",
            },
            {
                "rank": 4,
                "name_vi": "Cá Phổi",
                "name_en": "Lungfish",
                "stat": "Ngủ bùn",
                "detail_vi": "vùi mình trong bùn khô và giảm trao đổi chất nhiều tháng",
            },
            {
                "rank": 5,
                "name_vi": "Chim Cánh Cụt Hoàng Đế",
                "name_en": "Emperor penguin",
                "stat": "Băng giá",
                "detail_vi": "tụ thành đàn giữ nhiệt qua mùa đông Nam Cực khắc nghiệt",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_surprising_parenting_animals",
        "subject_vi": "Top 5 ông bố bà mẹ tận tụy trong thế giới động vật",
        "subject_en": "Top 5 surprising animal parents",
        "comparison_angle": "parenting",
        "items": [
            {
                "rank": 1,
                "name_vi": "Chim Cánh Cụt Hoàng Đế",
                "name_en": "Emperor penguin",
                "stat": "Ấp trứng",
                "detail_vi": "con đực giữ trứng trên chân qua mùa đông băng giá",
            },
            {
                "rank": 2,
                "name_vi": "Cá Ngựa",
                "name_en": "Seahorse",
                "stat": "Con đực mang thai",
                "detail_vi": "con cái gửi trứng vào túi ấp của con đực",
            },
            {
                "rank": 3,
                "name_vi": "Cá Sấu",
                "name_en": "Crocodile",
                "stat": "Bảo vệ con",
                "detail_vi": "mẹ cá sấu ngậm con rất nhẹ để đưa xuống nước",
            },
            {
                "rank": 4,
                "name_vi": "Ếch Phi Tiêu Độc",
                "name_en": "Poison dart frog",
                "stat": "Cõng nòng nọc",
                "detail_vi": "bố mẹ chở nòng nọc tới vũng nước nhỏ an toàn",
            },
            {
                "rank": 5,
                "name_vi": "Voi",
                "name_en": "Elephant",
                "stat": "Cả đàn chăm",
                "detail_vi": "voi con được mẹ, dì và cả đàn cùng bảo vệ",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_alien_deep_sea_animals",
        "subject_vi": "Top 5 sinh vật biển nhìn như người ngoài hành tinh",
        "subject_en": "Top 5 deep-sea animals that look alien",
        "comparison_angle": "special ability",
        "items": [
            {
                "rank": 1,
                "name_vi": "Cá Mắt Thùng",
                "name_en": "Barreleye fish",
                "stat": "Đầu trong suốt",
                "detail_vi": "mắt hình ống nằm trong vòm đầu trong suốt",
            },
            {
                "rank": 2,
                "name_vi": "Cá Mập Yêu Tinh",
                "name_en": "Goblin shark",
                "stat": "Hàm phóng",
                "detail_vi": "hàm bật ra phía trước để chụp con mồi",
            },
            {
                "rank": 3,
                "name_vi": "Sứa Ma Khổng Lồ",
                "name_en": "Giant phantom jelly",
                "stat": "Tay dài",
                "detail_vi": "cánh tay mềm dài trôi trong bóng tối biển sâu",
            },
            {
                "rank": 4,
                "name_vi": "Mực Thủy Tinh",
                "name_en": "Glass squid",
                "stat": "Trong suốt",
                "detail_vi": "cơ thể gần như trong suốt để hòa vào nước tối",
            },
            {
                "rank": 5,
                "name_vi": "Giun Bomber",
                "name_en": "Bomber worm",
                "stat": "Bom sáng",
                "detail_vi": "thả túi phát sáng để đánh lạc hướng kẻ săn mồi",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_transparent_animals",
        "subject_vi": "Top 5 loài có cơ thể trong suốt như tàng hình",
        "subject_en": "Top 5 transparent animals that look invisible",
        "comparison_angle": "camouflage",
        "items": [
            {
                "rank": 1,
                "name_vi": "Mực Thủy Tinh",
                "name_en": "Glass squid",
                "stat": "Gần vô hình",
                "detail_vi": "cơ thể trong suốt giúp khó bị phát hiện trong biển sâu",
            },
            {
                "rank": 2,
                "name_vi": "Ếch Thủy Tinh",
                "name_en": "Glass frog",
                "stat": "Bụng trong",
                "detail_vi": "da bụng mờ cho thấy nội tạng bên trong",
            },
            {
                "rank": 3,
                "name_vi": "Amphipod Trong Suốt",
                "name_en": "Transparent amphipod",
                "stat": "Ẩn mình",
                "detail_vi": "cơ thể bé trong suốt lẫn vào làn nước mở",
            },
            {
                "rank": 4,
                "name_vi": "Cá Băng Nam Cực",
                "name_en": "Antarctic icefish",
                "stat": "Máu nhạt",
                "detail_vi": "máu gần như không đỏ vì thiếu hemoglobin",
            },
            {
                "rank": 5,
                "name_vi": "Sứa Lược",
                "name_en": "Comb jelly",
                "stat": "Ánh cầu vồng",
                "detail_vi": "thân trong suốt phản chiếu dải sáng như neon",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_bioluminescence_survival_tricks",
        "subject_vi": "Top 5 sinh vật tự phát sáng để sinh tồn",
        "subject_en": "Top 5 animals using bioluminescence to survive",
        "comparison_angle": "bioluminescence",
        "items": [
            {
                "rank": 1,
                "name_vi": "Sứa Ống Biển",
                "name_en": "Siphonophore",
                "stat": "Chuỗi sáng",
                "detail_vi": "nhiều cá thể nối thành chuỗi săn mồi phát sáng",
            },
            {
                "rank": 2,
                "name_vi": "Cá Cần Câu",
                "name_en": "Anglerfish",
                "stat": "Đèn mồi",
                "detail_vi": "mồi phát sáng dụ con mồi lại gần miệng",
            },
            {
                "rank": 3,
                "name_vi": "Đom Đóm",
                "name_en": "Firefly",
                "stat": "Tín hiệu yêu",
                "detail_vi": "nhấp nháy để tìm bạn tình đúng loài",
            },
            {
                "rank": 4,
                "name_vi": "Mực Phát Sáng",
                "name_en": "Firefly squid",
                "stat": "Đèn xanh",
                "detail_vi": "đốm sáng xanh giúp ngụy trang và giao tiếp",
            },
            {
                "rank": 5,
                "name_vi": "Giun Biển Phát Sáng",
                "name_en": "Bioluminescent marine worm",
                "stat": "Tia sáng",
                "detail_vi": "phát sáng để thu hút bạn tình hoặc gây rối kẻ thù",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_slime_weapons",
        "subject_vi": "Top 5 loài dùng chất nhầy như vũ khí",
        "subject_en": "Top 5 animals using slime as a weapon",
        "comparison_angle": "special ability",
        "items": [
            {
                "rank": 1,
                "name_vi": "Cá Mút Đá Hagfish",
                "name_en": "Hagfish",
                "stat": "Nhầy nghẹt",
                "detail_vi": "phóng chất nhầy nở ra làm nghẹt mang kẻ săn mồi",
            },
            {
                "rank": 2,
                "name_vi": "Ốc Sên",
                "name_en": "Snail",
                "stat": "Đường nhầy",
                "detail_vi": "lớp nhầy giúp trườn qua bề mặt thô ráp",
            },
            {
                "rank": 3,
                "name_vi": "Ếch Làm Tổ Bọt",
                "name_en": "Foam-nest frog",
                "stat": "Tổ bọt",
                "detail_vi": "đánh bọt nhầy thành tổ giữ ẩm cho trứng",
            },
            {
                "rank": 4,
                "name_vi": "Sâu Larvacean",
                "name_en": "Larvacean",
                "stat": "Nhà nhầy",
                "detail_vi": "xây nhà lọc thức ăn bằng chất nhầy quanh cơ thể",
            },
            {
                "rank": 5,
                "name_vi": "Hải Sâm",
                "name_en": "Sea cucumber",
                "stat": "Sợi dính",
                "detail_vi": "phóng sợi dính để làm rối kẻ săn mồi",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_weirdest_mouths",
        "subject_vi": "Top 5 cái miệng kỳ dị nhất tự nhiên",
        "subject_en": "Top 5 weirdest mouths in nature",
        "comparison_angle": "special ability",
        "items": [
            {
                "rank": 1,
                "name_vi": "Cá Mập Yêu Tinh",
                "name_en": "Goblin shark",
                "stat": "Hàm phóng",
                "detail_vi": "hàm lao ra phía trước như lò xo khi bắt mồi",
            },
            {
                "rank": 2,
                "name_vi": "Cá Moray",
                "name_en": "Moray eel",
                "stat": "Hàm phụ",
                "detail_vi": "hàm thứ hai trong họng kéo con mồi vào sâu hơn",
            },
            {
                "rank": 3,
                "name_vi": "Cá Mút Đá",
                "name_en": "Lamprey",
                "stat": "Miệng vòng",
                "detail_vi": "miệng tròn đầy răng bám chặt lên cơ thể vật chủ",
            },
            {
                "rank": 4,
                "name_vi": "Rùa Cá Sấu",
                "name_en": "Alligator snapping turtle",
                "stat": "Mồi lưỡi",
                "detail_vi": "lưỡi giống giun dụ cá bơi thẳng vào miệng",
            },
            {
                "rank": 5,
                "name_vi": "Ấu Trùng Chuồn Chuồn",
                "name_en": "Dragonfly nymph",
                "stat": "Mặt nạ phóng",
                "detail_vi": "hàm dưới bật ra cực nhanh để chộp con mồi",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_weird_animal_homes",
        "subject_vi": "Top 5 loài xây nhà kỳ quặc nhất",
        "subject_en": "Top 5 strangest animal homes",
        "comparison_angle": "building ability",
        "items": [
            {
                "rank": 1,
                "name_vi": "Sâu Larvacean",
                "name_en": "Larvacean",
                "stat": "Nhà nhầy",
                "detail_vi": "dựng nhà lọc thức ăn bằng lớp nhầy khổng lồ",
            },
            {
                "rank": 2,
                "name_vi": "Sâu Caddisfly",
                "name_en": "Caddisfly larva",
                "stat": "Áo đá",
                "detail_vi": "ghép cát, đá nhỏ và mảnh cây thành vỏ bảo vệ",
            },
            {
                "rank": 3,
                "name_vi": "Cua Ẩn Sĩ",
                "name_en": "Hermit crab",
                "stat": "Mượn vỏ",
                "detail_vi": "đổi nhà bằng vỏ ốc bỏ trống khi cơ thể lớn lên",
            },
            {
                "rank": 4,
                "name_vi": "Cá Nóc Đốm Trắng",
                "name_en": "White-spotted pufferfish",
                "stat": "Vòng cát",
                "detail_vi": "con đực vẽ vòng tròn cát để thu hút bạn tình",
            },
            {
                "rank": 5,
                "name_vi": "Chim Bowerbird",
                "name_en": "Bowerbird",
                "stat": "Nhà tán tỉnh",
                "detail_vi": "trang trí sân khấu bằng đồ màu sắc để gây ấn tượng",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_plants_that_trick_animals",
        "subject_vi": "Top 5 cây lừa động vật đỉnh nhất",
        "subject_en": "Top 5 plants that trick animals",
        "comparison_angle": "special ability",
        "items": [
            {
                "rank": 1,
                "name_vi": "Lan Giả Ong Cái",
                "name_en": "Bee orchid",
                "stat": "Giả bạn tình",
                "detail_vi": "hoa giống ong cái để dụ ong đực đến thụ phấn",
            },
            {
                "rank": 2,
                "name_vi": "Cây Nắp Ấm Lowii",
                "name_en": "Nepenthes lowii",
                "stat": "Bồn cầu cây",
                "detail_vi": "lấy dinh dưỡng từ phân chuột chù cây ghé ăn mật",
            },
            {
                "rank": 3,
                "name_vi": "Hoa Xác Thối",
                "name_en": "Corpse flower",
                "stat": "Mùi xác",
                "detail_vi": "giả mùi thịt thối để gọi ruồi và bọ đến",
            },
            {
                "rank": 4,
                "name_vi": "Cây Trinh Nữ",
                "name_en": "Sensitive plant",
                "stat": "Cụp lá",
                "detail_vi": "cụp lá khi chạm để giảm chú ý và mất nước",
            },
            {
                "rank": 5,
                "name_vi": "Cây Bắt Ruồi Venus",
                "name_en": "Venus flytrap",
                "stat": "Bẫy kẹp",
                "detail_vi": "chỉ khép bẫy khi lông cảm ứng bị chạm đúng nhịp",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_sex_changing_animals",
        "subject_vi": "Top 5 sinh vật đổi giới tính khi cần",
        "subject_en": "Top 5 animals that can change sex",
        "comparison_angle": "special ability",
        "items": [
            {
                "rank": 1,
                "name_vi": "Cá Hề",
                "name_en": "Clownfish",
                "stat": "Đực thành cái",
                "detail_vi": "con đực lớn nhất có thể chuyển thành cái khi cần",
            },
            {
                "rank": 2,
                "name_vi": "Cá Wrasse",
                "name_en": "Wrasse",
                "stat": "Cái thành đực",
                "detail_vi": "một số con cái đổi thành đực khi đàn thiếu thủ lĩnh",
            },
            {
                "rank": 3,
                "name_vi": "Cá Mó",
                "name_en": "Parrotfish",
                "stat": "Đổi vai",
                "detail_vi": "nhiều loài có thể đổi giới tính theo cấu trúc đàn",
            },
            {
                "rank": 4,
                "name_vi": "Hàu",
                "name_en": "Oyster",
                "stat": "Đổi mùa",
                "detail_vi": "có thể thay đổi chức năng sinh sản theo điều kiện sống",
            },
            {
                "rank": 5,
                "name_vi": "Sên Biển",
                "name_en": "Sea slug",
                "stat": "Linh hoạt",
                "detail_vi": "một số loài có hệ sinh sản linh hoạt rất khác thường",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_movie_like_hunting_tactics",
        "subject_vi": "Top 5 loài có chiến thuật săn mồi như phim",
        "subject_en": "Top 5 movie-like hunting tactics",
        "comparison_angle": "special ability",
        "items": [
            {
                "rank": 1,
                "name_vi": "Cá Cung Thủ",
                "name_en": "Archerfish",
                "stat": "Bắn nước",
                "detail_vi": "tính khúc xạ rồi bắn tia nước hạ côn trùng",
            },
            {
                "rank": 2,
                "name_vi": "Tôm Súng",
                "name_en": "Pistol shrimp",
                "stat": "Bong bóng sốc",
                "detail_vi": "búng càng tạo bong bóng sụp đổ gây choáng con mồi",
            },
            {
                "rank": 3,
                "name_vi": "Cá Cần Câu",
                "name_en": "Anglerfish",
                "stat": "Đèn dụ mồi",
                "detail_vi": "mồi phát sáng kéo con mồi lại gần miệng",
            },
            {
                "rank": 4,
                "name_vi": "Kiến Sư Tử",
                "name_en": "Antlion",
                "stat": "Hố cát",
                "detail_vi": "đào phễu cát khiến kiến trượt xuống bẫy",
            },
            {
                "rank": 5,
                "name_vi": "Cá Sấu",
                "name_en": "Crocodile",
                "stat": "Giả khúc gỗ",
                "detail_vi": "nằm im như vật vô tri để áp sát con mồi",
            },
        ],
    },
    {
        "topic_type": "comparison_top5",
        "topic_key": "top5_self_destruct_defenses",
        "subject_vi": "Top 5 sinh vật tự hủy để tự vệ",
        "subject_en": "Top 5 self-destruct defense tactics in nature",
        "comparison_angle": "special ability",
        "items": [
            {
                "rank": 1,
                "name_vi": "Kiến Nổ",
                "name_en": "Exploding ant",
                "stat": "Vỡ cơ thể",
                "detail_vi": "kiến thợ tự phá thân để phun chất dính bảo vệ tổ",
            },
            {
                "rank": 2,
                "name_vi": "Hải Sâm",
                "name_en": "Sea cucumber",
                "stat": "Phóng ruột",
                "detail_vi": "đẩy nội tạng hoặc sợi dính ra để đánh lạc hướng",
            },
            {
                "rank": 3,
                "name_vi": "Thằn Lằn",
                "name_en": "Lizard",
                "stat": "Rụng đuôi",
                "detail_vi": "bỏ lại chiếc đuôi còn giãy để thoát kẻ săn mồi",
            },
            {
                "rank": 4,
                "name_vi": "Bạch Tuộc",
                "name_en": "Octopus",
                "stat": "Màn mực",
                "detail_vi": "phun mực tạo đám mây che mắt rồi đổi hướng chạy",
            },
            {
                "rank": 5,
                "name_vi": "Bọ Bombardier",
                "name_en": "Bombardier beetle",
                "stat": "Xịt nóng",
                "detail_vi": "phun tia hóa chất nóng để đẩy lùi kẻ tấn công",
            },
        ],
    },
]

ANATOMY_TOPICS = [
    {
        "topic_type": "anatomy_infographic",
        "topic_key": "crab_anatomy_infographic",
        "subject_vi": "Giải phẫu con cua: bộ giáp mini dưới đáy nước",
        "subject_en": "Crab anatomy educational infographic",
        "animal_vi": "con cua",
        "animal_en": "crab",
        "hook_vi": "Nhìn con cua như một chiếc xe tăng tí hon, nhưng bên trong là cả bộ máy sống rất gọn.",
        "main_fact_vi": "Cua có mai cứng, càng khỏe, mang nằm dưới giáp và phần bụng gập sát dưới cơ thể.",
        "question_vi": "Bạn thấy bộ phận nào của cua giống thiết kế robot nhất?",
        "composition_en": "side view with slight top angle, large crab centered and filling most of the image, claws visible, legs spread naturally",
        "transparency_en": "slightly semi-transparent shell around the chest and abdomen so gills and internal organs can be seen while the crab remains realistic",
        "background_en": "simple light grey-blue background, clean and minimal, no texture, no decoration",
        "labels": [
            {
                "label_vi": "mắt cua",
                "target_en": "the small eyes on short stalks",
                "description_vi": "mắt nằm trên cuống ngắn để quan sát rộng",
            },
            {
                "label_vi": "râu cua",
                "target_en": "the short antennae near the mouth",
                "description_vi": "râu ngắn giúp cảm nhận môi trường xung quanh",
            },
            {
                "label_vi": "miệng",
                "target_en": "the mouthparts under the front shell",
                "description_vi": "vùng miệng nằm dưới phần trước của mai",
            },
            {
                "label_vi": "càng cua",
                "target_en": "the large front claws",
                "description_vi": "cặp càng dùng để kẹp, tự vệ và lấy thức ăn",
            },
            {
                "label_vi": "mang",
                "target_en": "the gill area under the side of the carapace",
                "description_vi": "mang nằm dưới mai giúp cua hô hấp trong nước",
            },
            {
                "label_vi": "chân bò",
                "target_en": "the walking legs on both sides of the body",
                "description_vi": "các chân bên giúp cua bò ngang rất linh hoạt",
            },
            {
                "label_vi": "mai cua",
                "target_en": "the hard carapace covering the body",
                "description_vi": "lớp giáp cứng bảo vệ phần thân bên trong",
            },
            {
                "label_vi": "gan tụy",
                "target_en": "the yellow digestive gland inside the body",
                "description_vi": "cơ quan tiêu hóa màu vàng nằm dưới mai",
            },
            {
                "label_vi": "đường ruột",
                "target_en": "the dark intestine running toward the folded abdomen",
                "description_vi": "đường ruột sẫm chạy về phía bụng gập",
            },
            {
                "label_vi": "bụng gập",
                "target_en": "the folded abdomen tucked under the body",
                "description_vi": "phần bụng gập sát dưới thân cua",
            },
        ],
    },
    {
        "topic_type": "anatomy_infographic",
        "topic_key": "squid_anatomy_infographic",
        "subject_vi": "Giải phẫu con mực: chiếc phản lực mềm dưới biển",
        "subject_en": "Squid anatomy educational infographic",
        "animal_vi": "con mực",
        "animal_en": "squid",
        "hook_vi": "Con mực không chỉ có nhiều tay; nó còn bơi như một chiếc phản lực mini.",
        "main_fact_vi": "Mực dùng phễu nước để phun nước di chuyển, có túi mực để đánh lạc hướng và mang nằm trong áo mực.",
        "question_vi": "Bạn tò mò nhất về túi mực hay phễu nước?",
        "composition_en": "side view, streamlined squid body centered diagonally, head and arms visible on one side, fins and mantle clearly shown",
        "transparency_en": "slightly semi-transparent mantle so gills, ink sac, stomach, heart, and digestive tract are visible without looking artificial",
        "background_en": "simple light grey-blue background, clean and minimal, no texture, no decoration",
        "labels": [
            {
                "label_vi": "mắt mực",
                "target_en": "the large eye on the side of the head",
                "description_vi": "mắt lớn giúp quan sát trong môi trường nước",
            },
            {
                "label_vi": "tay mực",
                "target_en": "the shorter arms around the mouth",
                "description_vi": "các tay ngắn giữ và kéo con mồi",
            },
            {
                "label_vi": "tua dài",
                "target_en": "the two long feeding tentacles",
                "description_vi": "hai tua dài dùng để chộp mồi từ xa",
            },
            {
                "label_vi": "miệng mỏ",
                "target_en": "the beak-like mouth at the center of the arms",
                "description_vi": "miệng dạng mỏ cứng nằm giữa vòng tay",
            },
            {
                "label_vi": "phễu nước",
                "target_en": "the siphon funnel below the head",
                "description_vi": "phễu phun nước giúp mực đổi hướng và tăng tốc",
            },
            {
                "label_vi": "áo mực",
                "target_en": "the mantle body",
                "description_vi": "phần thân chính bao bọc nhiều cơ quan bên trong",
            },
            {
                "label_vi": "mang",
                "target_en": "the pair of gills inside the mantle",
                "description_vi": "mang nằm trong áo mực để lấy oxy từ nước",
            },
            {
                "label_vi": "túi mực",
                "target_en": "the dark ink sac inside the mantle",
                "description_vi": "túi chứa mực đen để tạo màn che khi nguy hiểm",
            },
            {
                "label_vi": "tim",
                "target_en": "the heart area near the gills",
                "description_vi": "tim bơm máu qua hệ tuần hoàn của mực",
            },
            {
                "label_vi": "vây mực",
                "target_en": "the side fins on the mantle",
                "description_vi": "vây giúp mực giữ thăng bằng khi bơi chậm",
            },
        ],
    },
    {
        "topic_type": "anatomy_infographic",
        "topic_key": "frog_anatomy_infographic",
        "subject_vi": "Giải phẫu con ếch: chuyên gia nhảy và thở bằng da",
        "subject_en": "Frog anatomy educational infographic",
        "animal_vi": "con ếch",
        "animal_en": "frog",
        "hook_vi": "Con ếch nhìn ngồi im vậy thôi, nhưng cơ thể nó là bộ máy nhảy, nuốt và thở rất lạ.",
        "main_fact_vi": "Ếch có chân sau khỏe để bật nhảy, da ẩm hỗ trợ hô hấp, lưỡi dính và phổi nằm trong khoang thân.",
        "question_vi": "Bạn thấy lưỡi ếch hay da ếch kỳ lạ hơn?",
        "composition_en": "side view frog in a natural crouching pose, centered and filling most of the image, legs visible and body slightly translucent",
        "transparency_en": "semi-transparent torso so heart, lungs, stomach, and intestines are visible while external skin and legs remain realistic",
        "background_en": "simple light grey-blue background, clean and minimal, no texture, no decoration",
        "labels": [
            {
                "label_vi": "mắt ếch",
                "target_en": "the raised eye on top of the head",
                "description_vi": "mắt nhô cao giúp quan sát khi nổi trên mặt nước",
            },
            {
                "label_vi": "màng nhĩ",
                "target_en": "the round tympanum behind the eye",
                "description_vi": "màng tròn sau mắt giúp tiếp nhận âm thanh",
            },
            {
                "label_vi": "lưỡi dính",
                "target_en": "the sticky tongue inside the mouth",
                "description_vi": "lưỡi dính bật ra để bắt côn trùng",
            },
            {
                "label_vi": "da ẩm",
                "target_en": "the moist skin surface",
                "description_vi": "da ẩm hỗ trợ trao đổi khí ngoài phổi",
            },
            {
                "label_vi": "phổi",
                "target_en": "the lungs inside the chest cavity",
                "description_vi": "phổi giúp ếch hô hấp khi ở trên cạn",
            },
            {
                "label_vi": "tim",
                "target_en": "the heart area between the lungs",
                "description_vi": "tim nằm trong khoang ngực giữa hai phổi",
            },
            {
                "label_vi": "dạ dày",
                "target_en": "the stomach inside the abdomen",
                "description_vi": "dạ dày tiêu hóa con mồi sau khi nuốt",
            },
            {
                "label_vi": "ruột",
                "target_en": "the coiled intestine in the abdomen",
                "description_vi": "ruột cuộn trong bụng để hấp thụ dinh dưỡng",
            },
            {
                "label_vi": "chân trước",
                "target_en": "the front leg",
                "description_vi": "chân trước đỡ cơ thể khi tiếp đất",
            },
            {
                "label_vi": "chân sau",
                "target_en": "the long muscular hind leg",
                "description_vi": "chân sau dài và khỏe để bật nhảy",
            },
        ],
    },
]


SINGLE_TOPICS = [
    {
        "topic_type": "single_card",
        "topic_key": "cheetah_speed_card",
        "subject_vi": "Báo Săn",
        "subject_en": "Cheetah",
        "fact_label": "speed",
        "fact_value": "110 km/h",
        "fact_detail": "one of the fastest land animals on Earth",
        "detail_vi": "có thể bứt tốc cực nhanh trong vài giây ngắn",
    },
    {
        "topic_type": "single_card",
        "topic_key": "mantis_shrimp_punch_card",
        "subject_vi": "Tôm Tít",
        "subject_en": "Mantis shrimp",
        "fact_label": "special ability",
        "fact_value": "cú đấm siêu tốc",
        "fact_detail": "its strike is among the fastest animal movements and can crack shells",
        "detail_vi": "cú đấm tạo lực mạnh đến mức có thể làm nứt vỏ con mồi",
    },
    {
        "topic_type": "single_card",
        "topic_key": "electric_eel_shock_card",
        "subject_vi": "Lươn Điện",
        "subject_en": "Electric eel",
        "fact_label": "special ability",
        "fact_value": "phóng điện mạnh",
        "fact_detail": "it can generate powerful electric pulses to hunt and defend itself",
        "detail_vi": "dùng xung điện mạnh để săn mồi và tự vệ dưới nước",
    },
    {
        "topic_type": "single_card",
        "topic_key": "immortal_jellyfish_card",
        "subject_vi": "Sứa Bất Tử",
        "subject_en": "Immortal jellyfish",
        "fact_label": "special ability",
        "fact_value": "đảo ngược tuổi",
        "fact_detail": "it can revert to an earlier life stage under stress",
        "detail_vi": "khi gặp căng thẳng, nó có thể quay về giai đoạn non hơn",
    },
    {
        "topic_type": "single_card",
        "topic_key": "axolotl_regeneration_card",
        "subject_vi": "Kỳ Giông Mexico",
        "subject_en": "Axolotl",
        "fact_label": "regeneration",
        "fact_value": "tái tạo chi",
        "fact_detail": "it can regrow limbs and repair parts of its body with unusual ability",
        "detail_vi": "có thể mọc lại chi và sửa chữa một số mô bị tổn thương",
    },
    {
        "topic_type": "single_card",
        "topic_key": "archerfish_water_shot_card",
        "subject_vi": "Cá Mang Rổ",
        "subject_en": "Archerfish",
        "fact_label": "hunting ability",
        "fact_value": "bắn tia nước",
        "fact_detail": "it shoots water jets to knock insects off branches above the surface",
        "detail_vi": "bắn tia nước chính xác để hạ côn trùng trên cành cây",
    },
    {
        "topic_type": "single_card",
        "topic_key": "mimic_octopus_card",
        "subject_vi": "Bạch Tuộc Bắt Chước",
        "subject_en": "Mimic octopus",
        "fact_label": "camouflage",
        "fact_value": "giả dạng bậc thầy",
        "fact_detail": "it can imitate the look and movement of several dangerous sea animals",
        "detail_vi": "bắt chước hình dáng và cách di chuyển của loài biển nguy hiểm",
    },
    {
        "topic_type": "single_card",
        "topic_key": "lyrebird_voice_card",
        "subject_vi": "Chim Lia",
        "subject_en": "Lyrebird",
        "fact_label": "sound mimicry",
        "fact_value": "nhại âm siêu thật",
        "fact_detail": "it is famous for copying natural and artificial sounds with striking accuracy",
        "detail_vi": "có thể bắt chước nhiều âm thanh tự nhiên và nhân tạo rất giống",
    },
    {
        "topic_type": "single_card",
        "topic_key": "pangolin_armor_card",
        "subject_vi": "Tê Tê",
        "subject_en": "Pangolin",
        "fact_label": "defense",
        "fact_value": "áo giáp vảy",
        "fact_detail": "its keratin scales help it curl into a tough defensive ball",
        "detail_vi": "cuộn tròn thành quả bóng vảy cứng để tự bảo vệ",
    },
    {
        "topic_type": "single_card",
        "topic_key": "tardigrade_survival_card",
        "subject_vi": "Gấu Nước",
        "subject_en": "Tardigrade",
        "fact_label": "survival",
        "fact_value": "sống cực hạn",
        "fact_detail": "it can survive extreme environments by entering a dormant state",
        "detail_vi": "chuyển sang trạng thái ngủ sâu để chịu điều kiện khắc nghiệt",
    },
    {
        "topic_type": "single_card",
        "topic_key": "corpse_flower_card",
        "subject_vi": "Hoa Xác Thối",
        "subject_en": "Corpse flower",
        "fact_label": "plant ability",
        "fact_value": "mùi xác thối",
        "fact_detail": "its odor attracts pollinators that are drawn to decaying organic matter",
        "detail_vi": "tỏa mùi giống xác thối để thu hút côn trùng thụ phấn",
    },
    {
        "topic_type": "single_card",
        "topic_key": "rafflesia_giant_flower_card",
        "subject_vi": "Hoa Rafflesia",
        "subject_en": "Rafflesia flower",
        "fact_label": "plant record",
        "fact_value": "hoa khổng lồ",
        "fact_detail": "it produces one of the largest individual flowers in the world",
        "detail_vi": "tạo ra một trong những bông hoa đơn lẻ lớn nhất thế giới",
    },
    {
        "topic_type": "single_card",
        "topic_key": "dragon_blood_tree_card",
        "subject_vi": "Cây Máu Rồng",
        "subject_en": "Dragon blood tree",
        "fact_label": "plant feature",
        "fact_value": "nhựa đỏ",
        "fact_detail": "its red resin gives the tree its dramatic name and unusual appearance",
        "detail_vi": "nhựa cây màu đỏ khiến nó có vẻ ngoài rất kỳ lạ",
    },
    {
        "topic_type": "single_card",
        "topic_key": "owl_silent_flight_card",
        "subject_vi": "Cú Mèo",
        "subject_en": "Owl",
        "fact_label": "special ability",
        "fact_value": "bay gần như im lặng",
        "fact_detail": "its wing structure helps reduce turbulence and noise",
        "detail_vi": "cấu trúc lông cánh giúp giảm tiếng động khi lao xuống săn mồi",
    },
    {
        "topic_type": "single_card",
        "topic_key": "exploding_ant_defense_card",
        "subject_vi": "Kiến Nổ",
        "subject_en": "Exploding ant",
        "fact_label": "defense",
        "fact_value": "tự nổ bảo vệ đàn",
        "fact_detail": "some worker ants rupture their own bodies to release sticky defensive fluid",
        "detail_vi": "một số kiến thợ hy sinh thân mình để phun chất dính bảo vệ tổ",
    },
    {
        "topic_type": "single_card",
        "topic_key": "venus_flytrap_card",
        "subject_vi": "Cây Bắt Ruồi Venus",
        "subject_en": "Venus flytrap",
        "fact_label": "special ability",
        "fact_value": "cây ăn thịt",
        "fact_detail": "it traps insects with a fast snap-trap mechanism",
        "detail_vi": "khép bẫy rất nhanh để giữ côn trùng làm nguồn dinh dưỡng",
    },
    {
        "topic_type": "single_card",
        "topic_key": "barreleye_transparent_head_card",
        "subject_vi": "Cá Mắt Thùng",
        "subject_en": "Barreleye fish",
        "fact_label": "transparent head",
        "fact_value": "đầu trong suốt",
        "fact_detail": "its transparent head dome lets its tubular eyes look upward through the skull-like shield",
        "detail_vi": "mắt hình ống nằm trong vòm đầu trong suốt để nhìn con mồi phía trên",
    },
    {
        "topic_type": "single_card",
        "topic_key": "goblin_shark_slingshot_jaw_card",
        "subject_vi": "Cá Mập Yêu Tinh",
        "subject_en": "Goblin shark",
        "fact_label": "jaw strike",
        "fact_value": "hàm phóng ra",
        "fact_detail": "its jaws can shoot forward quickly to snatch prey in deep water",
        "detail_vi": "hàm bật ra phía trước như lò xo để chụp con mồi",
    },
    {
        "topic_type": "single_card",
        "topic_key": "hagfish_slime_card",
        "subject_vi": "Cá Mút Đá Hagfish",
        "subject_en": "Hagfish",
        "fact_label": "slime defense",
        "fact_value": "nhầy nghẹt mang",
        "fact_detail": "it releases slime that expands in seawater and can clog predator gills",
        "detail_vi": "chất nhầy nở mạnh trong nước biển làm kẻ săn mồi khó thở",
    },
    {
        "topic_type": "single_card",
        "topic_key": "pistol_shrimp_snap_card",
        "subject_vi": "Tôm Súng",
        "subject_en": "Pistol shrimp",
        "fact_label": "shock bubble",
        "fact_value": "bong bóng sốc",
        "fact_detail": "its claw snap creates a collapsing bubble that can stun small prey",
        "detail_vi": "cú búng càng tạo bong bóng sụp đổ làm choáng con mồi nhỏ",
    },
    {
        "topic_type": "single_card",
        "topic_key": "bombardier_beetle_hot_spray_card",
        "subject_vi": "Bọ Bombardier",
        "subject_en": "Bombardier beetle",
        "fact_label": "chemical defense",
        "fact_value": "xịt hóa chất nóng",
        "fact_detail": "it sprays a hot chemical burst from its abdomen to deter attackers",
        "detail_vi": "phun tia hóa chất nóng từ bụng để đẩy lùi kẻ tấn công",
    },
    {
        "topic_type": "single_card",
        "topic_key": "glass_frog_translucent_body_card",
        "subject_vi": "Ếch Thủy Tinh",
        "subject_en": "Glass frog",
        "fact_label": "transparent body",
        "fact_value": "bụng trong suốt",
        "fact_detail": "its translucent underside can reveal organs and helps it blend with leaves",
        "detail_vi": "bụng mờ cho thấy nội tạng và giúp hòa vào lá cây",
    },
    {
        "topic_type": "single_card",
        "topic_key": "larvacean_mucus_house_card",
        "subject_vi": "Sâu Larvacean",
        "subject_en": "Larvacean",
        "fact_label": "mucus house",
        "fact_value": "nhà nhầy",
        "fact_detail": "it builds a mucus house around itself to filter tiny food particles from water",
        "detail_vi": "xây nhà nhầy quanh cơ thể để lọc hạt thức ăn cực nhỏ",
    },
    {
        "topic_type": "single_card",
        "topic_key": "nepenthes_lowii_tree_shrew_card",
        "subject_vi": "Cây Nắp Ấm Lowii",
        "subject_en": "Nepenthes lowii",
        "fact_label": "plant nutrition",
        "fact_value": "bồn cầu cây",
        "fact_detail": "it can gain nutrients from tree shrew droppings left near its pitcher",
        "detail_vi": "dụ chuột chù cây ăn mật rồi lấy dinh dưỡng từ phân",
    },
    {
        "topic_type": "single_card",
        "topic_key": "hydnora_africana_underground_flower_card",
        "subject_vi": "Hydnora Africana",
        "subject_en": "Hydnora africana",
        "fact_label": "parasitic plant",
        "fact_value": "hoa dưới đất",
        "fact_detail": "this parasitic plant lives mostly underground and uses odor to attract beetles",
        "detail_vi": "sống dưới đất, hoa bốc mùi để dụ bọ đến thụ phấn",
    },
    {
        "topic_type": "single_card",
        "topic_key": "welwitschia_two_leaves_card",
        "subject_vi": "Cây Welwitschia",
        "subject_en": "Welwitschia",
        "fact_label": "desert survival",
        "fact_value": "hai lá sống lâu",
        "fact_detail": "it grows two long leaves throughout its life and can persist in harsh desert conditions",
        "detail_vi": "gần như chỉ có hai lá lớn tiếp tục mọc suốt đời trong sa mạc",
    },
]


MATCHUP_TOPICS = [
    {
        "topic_type": "matchup_versus",
        "topic_key": "tibetan_mastiff_vs_caucasian_shepherd",
        "subject_vi": "Chó Ngao Tây Tạng so tài Chó Chăn Cừu Kavkaz",
        "subject_en": "Tibetan Mastiff versus Caucasian Shepherd",
        "left": {
            "name_vi": "Chó Ngao Tây Tạng",
            "name_en": "Tibetan Mastiff",
            "height": "76 cm",
            "weight": "70 kg",
            "bite_force": "Lực hàm mạnh",
            "edge_vi": "lông cổ dày, tiếng sủa uy hiếp, bản năng canh gác",
        },
        "right": {
            "name_vi": "Chó Chăn Cừu Kavkaz",
            "name_en": "Caucasian Shepherd",
            "height": "75 cm",
            "weight": "75 kg",
            "bite_force": "Lực hàm mạnh",
            "edge_vi": "thân dày, gan lì, phản xạ bảo vệ lãnh thổ",
        },
        "verdict_vi": "Hai giống chó khá ngang thể hình; khác biệt nằm ở lối canh gác, độ lì và phản xạ bảo vệ.",
        "reality_note_vi": "Đây là so sánh kiến thức về giống chó, không cổ vũ cho chó đối đầu thật.",
        "debate_question_vi": "Bạn chọn vẻ uy nghi của Ngao Tây Tạng hay độ lì của Kavkaz?",
    },
    {
        "topic_type": "matchup_versus",
        "topic_key": "dingo_vs_coyote",
        "subject_vi": "Chó Dingo so tài Sói Đồng Cỏ",
        "subject_en": "Dingo versus coyote",
        "left": {
            "name_vi": "Chó Dingo",
            "name_en": "Dingo",
            "height": "60 cm",
            "weight": "18 kg",
            "bite_force": "Sức bền tốt",
            "edge_vi": "săn mồi linh hoạt, chịu nóng tốt, di chuyển bền bỉ",
        },
        "right": {
            "name_vi": "Sói Đồng Cỏ",
            "name_en": "Coyote",
            "height": "60 cm",
            "weight": "18 kg",
            "bite_force": "Nhanh nhẹn",
            "edge_vi": "linh hoạt, thích nghi tốt, di chuyển khéo trong địa hình mở",
        },
        "verdict_vi": "Chó dingo và sói đồng cỏ khá ngang tầm; dingo nhỉnh ở sức bền, sói đồng cỏ nổi bật ở độ lanh lợi.",
        "reality_note_vi": "Đây là so sánh đặc điểm giữa hai loài họ chó cỡ trung, không cổ vũ đối đầu thật.",
        "debate_question_vi": "Bạn chọn sức bền của dingo hay sự khôn lanh của sói đồng cỏ?",
    },
    {
        "topic_type": "matchup_versus",
        "topic_key": "jaguar_vs_leopard",
        "subject_vi": "Báo Đốm Mỹ so tài Báo Hoa Mai",
        "subject_en": "Jaguar versus leopard",
        "left": {
            "name_vi": "Báo Đốm Mỹ",
            "name_en": "Jaguar",
            "height": "75 cm",
            "weight": "90 kg",
            "bite_force": "Cắn xuyên sọ",
            "edge_vi": "hàm cực khỏe, thân chắc, giỏi phục kích gần nước",
        },
        "right": {
            "name_vi": "Báo Hoa Mai",
            "name_en": "Leopard",
            "height": "70 cm",
            "weight": "70 kg",
            "bite_force": "Leo cây giỏi",
            "edge_vi": "nhẹ hơn, cực linh hoạt, kéo mồi lên cây rất khỏe",
        },
        "verdict_vi": "Báo đốm Mỹ lợi thế về lực hàm, còn báo hoa mai nổi bật ở độ linh hoạt và kỹ năng leo cây.",
        "reality_note_vi": "Đây là so sánh đặc điểm sinh học giữa hai loài mèo lớn, không cổ vũ đối đầu thật.",
        "debate_question_vi": "Bạn chọn lực hàm của báo đốm hay độ khéo của báo hoa mai?",
    },
    {
        "topic_type": "matchup_versus",
        "topic_key": "great_white_shark_vs_tiger_shark",
        "subject_vi": "Cá Mập Trắng so tài Cá Mập Hổ",
        "subject_en": "Great white shark versus tiger shark",
        "left": {
            "name_vi": "Cá Mập Trắng",
            "name_en": "Great white shark",
            "height": "Dài 4.5 m",
            "weight": "900 kg",
            "bite_force": "Cú cắn mạnh",
            "edge_vi": "tốc độ bứt phá, lực cắn lớn, săn mồi bằng cú lao nhanh",
        },
        "right": {
            "name_vi": "Cá Mập Hổ",
            "name_en": "Tiger shark",
            "height": "Dài 4 m",
            "weight": "850 kg",
            "bite_force": "Ăn tạp khỏe",
            "edge_vi": "hàm răng cưa, ăn đa dạng, cực lì trong môi trường biển",
        },
        "verdict_vi": "Cá mập trắng nổi bật ở cú lao săn mồi, còn cá mập hổ đáng nể vì độ lì và khẩu phần cực rộng.",
        "reality_note_vi": "Đây là so sánh đặc điểm sinh học giữa hai loài cá mập lớn, không cổ vũ đối đầu thật.",
        "debate_question_vi": "Bạn thấy cú lao của cá mập trắng hay độ lì của cá mập hổ đáng sợ hơn?",
    },
    {
        "topic_type": "matchup_versus",
        "topic_key": "goblin_shark_vs_ghost_shark",
        "subject_vi": "Cá Mập Yêu Tinh so tài Cá Mập Ma",
        "subject_en": "Goblin shark versus ghost shark",
        "left": {
            "name_vi": "Cá Mập Yêu Tinh",
            "name_en": "Goblin shark",
            "measure_label": "Chiều dài",
            "height": "3-4 m",
            "weight": "160 kg",
            "bite_force": "Hàm phóng",
            "edge_vi": "hàm bật ra nhanh, mõm dài cảm nhận tín hiệu con mồi",
        },
        "right": {
            "name_vi": "Cá Mập Ma",
            "name_en": "Ghost shark",
            "measure_label": "Chiều dài",
            "height": "1-1.5 m",
            "weight": "Nhẹ hơn",
            "bite_force": "Răng nghiền",
            "edge_vi": "cơ thể lạ, sống tầng sâu, nghiền vỏ con mồi nhỏ",
        },
        "verdict_vi": "Cá mập yêu tinh nổi bật ở cú phóng hàm, còn cá mập ma kỳ dị ở hình dạng và cách kiếm ăn tầng sâu.",
        "reality_note_vi": "Đây là so sánh đặc điểm biển sâu, không cổ vũ động vật đối đầu thật.",
        "debate_question_vi": "Bạn thấy con nào giống sinh vật ngoài hành tinh hơn?",
    },
    {
        "topic_type": "matchup_versus",
        "topic_key": "mantis_shrimp_vs_pistol_shrimp",
        "subject_vi": "Tôm Tít so tài Tôm Súng",
        "subject_en": "Mantis shrimp versus pistol shrimp",
        "left": {
            "name_vi": "Tôm Tít",
            "name_en": "Mantis shrimp",
            "measure_label": "Chiều dài",
            "height": "10-30 cm",
            "weight": "Nhỏ",
            "bite_force": "Cú đấm nhanh",
            "edge_vi": "cú đấm cực tốc, mắt phức tạp, phá vỏ con mồi",
        },
        "right": {
            "name_vi": "Tôm Súng",
            "name_en": "Pistol shrimp",
            "measure_label": "Chiều dài",
            "height": "3-5 cm",
            "weight": "Rất nhỏ",
            "bite_force": "Bong bóng sốc",
            "edge_vi": "búng càng tạo bong bóng sụp đổ làm choáng con mồi",
        },
        "verdict_vi": "Tôm tít mạnh ở cú đấm trực diện, còn tôm súng gây ấn tượng bằng bong bóng sốc siêu nhỏ mà rất lợi hại.",
        "reality_note_vi": "Đây là so sánh cơ chế săn mồi của hai loài giáp xác, không cổ vũ đối đầu thật.",
        "debate_question_vi": "Bạn chọn cú đấm của tôm tít hay cú búng của tôm súng?",
    },
    {
        "topic_type": "matchup_versus",
        "topic_key": "clownfish_vs_damselfish",
        "subject_vi": "Cá Hề so tài Cá Thia",
        "subject_en": "Clownfish versus damselfish",
        "left": {
            "name_vi": "Cá Hề",
            "name_en": "Clownfish",
            "measure_label": "Chiều dài",
            "height": "10 cm",
            "weight": "Nhỏ",
            "bite_force": "Sống cùng hải quỳ",
            "edge_vi": "lớp nhầy giúp sống giữa xúc tu hải quỳ",
        },
        "right": {
            "name_vi": "Cá Thia",
            "name_en": "Damselfish",
            "measure_label": "Chiều dài",
            "height": "8-15 cm",
            "weight": "Nhỏ",
            "bite_force": "Giữ lãnh thổ",
            "edge_vi": "bảo vệ vùng sống quyết liệt, thích nghi tốt ở rạn san hô",
        },
        "verdict_vi": "Cá hề nổi bật ở cộng sinh với hải quỳ, còn cá thia đáng nể ở khả năng giữ lãnh thổ.",
        "reality_note_vi": "Đây là so sánh chiến thuật sống ở rạn san hô, không cổ vũ động vật đối đầu thật.",
        "debate_question_vi": "Bạn thích chiến thuật sống chung hay giữ lãnh thổ hơn?",
    },
    {
        "topic_type": "matchup_versus",
        "topic_key": "owl_vs_bat_night_hunters",
        "subject_vi": "Cú Mèo so tài Dơi",
        "subject_en": "Owl versus bat night hunters",
        "left": {
            "name_vi": "Cú Mèo",
            "name_en": "Owl",
            "measure_label": "Sải cánh",
            "height": "0.8-1.5 m",
            "weight": "0.5-2 kg",
            "bite_force": "Bay êm",
            "edge_vi": "lông cánh giảm tiếng động, thị giác và thính giác rất tốt",
        },
        "right": {
            "name_vi": "Dơi",
            "name_en": "Bat",
            "measure_label": "Sải cánh",
            "height": "20-40 cm",
            "weight": "Rất nhẹ",
            "bite_force": "Định vị âm",
            "edge_vi": "phát siêu âm rồi nghe tiếng vọng để bay và săn trong tối",
        },
        "verdict_vi": "Cú mèo mạnh ở bay êm và phục kích, còn dơi nổi bật ở định vị âm trong bóng tối.",
        "reality_note_vi": "Đây là so sánh hai chiến thuật săn đêm, không cổ vũ đối đầu thật.",
        "debate_question_vi": "Bạn chọn đôi cánh im lặng hay radar sinh học?",
    },
    {
        "topic_type": "matchup_versus",
        "topic_key": "caiman_vs_alligator",
        "subject_vi": "Cá Sấu Caiman so tài Cá Sấu Mõm Ngắn",
        "subject_en": "Caiman versus alligator",
        "left": {
            "name_vi": "Cá Sấu Caiman",
            "name_en": "Caiman",
            "measure_label": "Chiều dài",
            "height": "1.5-2.5 m",
            "weight": "40 kg",
            "bite_force": "Hàm khỏe",
            "edge_vi": "nhỏ gọn, linh hoạt, phục kích tốt trong vùng nước ngọt",
        },
        "right": {
            "name_vi": "Cá Sấu Mõm Ngắn",
            "name_en": "Alligator",
            "measure_label": "Chiều dài",
            "height": "3-4 m",
            "weight": "230 kg",
            "bite_force": "Hàm rất khỏe",
            "edge_vi": "to hơn, lực hàm mạnh, giỏi phục kích ở đầm lầy",
        },
        "verdict_vi": "Alligator nhỉnh ở kích thước và lực hàm, caiman nổi bật ở sự gọn nhẹ và linh hoạt.",
        "reality_note_vi": "Đây là so sánh đặc điểm sinh học của hai nhóm cá sấu, không cổ vũ đối đầu thật.",
        "debate_question_vi": "Bạn thấy xe tăng mini nào đáng gờm hơn?",
    },
    {
        "topic_type": "matchup_versus",
        "topic_key": "king_cobra_vs_black_mamba",
        "subject_vi": "Rắn Hổ Mang Chúa so tài Mamba Đen",
        "subject_en": "King cobra versus black mamba",
        "left": {
            "name_vi": "Rắn Hổ Mang Chúa",
            "name_en": "King cobra",
            "measure_label": "Chiều dài",
            "height": "3-4 m",
            "weight": "6 kg",
            "bite_force": "Nọc thần kinh",
            "edge_vi": "rất dài, dựng phần thân trước và kiểm soát khoảng cách tốt",
        },
        "right": {
            "name_vi": "Mamba Đen",
            "name_en": "Black mamba",
            "measure_label": "Chiều dài",
            "height": "2.5-3 m",
            "weight": "1.6 kg",
            "bite_force": "Nọc thần kinh",
            "edge_vi": "di chuyển rất nhanh, phản ứng nhạy và phòng vệ quyết liệt",
        },
        "verdict_vi": "Hổ mang chúa nhỉnh ở chiều dài và tầm kiểm soát, mamba đen nổi bật ở tốc độ và phản xạ.",
        "reality_note_vi": "Đây là so sánh kiến thức về rắn độc, không cổ vũ tiếp xúc hoặc đối đầu thật.",
        "debate_question_vi": "Bạn thấy lợi thế chiều dài hay tốc độ đáng sợ hơn?",
    },
    {
        "topic_type": "matchup_versus",
        "topic_key": "snow_leopard_vs_clouded_leopard",
        "subject_vi": "Báo Tuyết so tài Báo Gấm",
        "subject_en": "Snow leopard versus clouded leopard",
        "left": {
            "name_vi": "Báo Tuyết",
            "name_en": "Snow leopard",
            "height": "60 cm",
            "weight": "45 kg",
            "bite_force": "Nhảy xa",
            "edge_vi": "đuôi dài giữ thăng bằng, thích nghi núi tuyết dốc cao",
        },
        "right": {
            "name_vi": "Báo Gấm",
            "name_en": "Clouded leopard",
            "height": "50 cm",
            "weight": "23 kg",
            "bite_force": "Răng nanh dài",
            "edge_vi": "leo cây cực giỏi, cổ chân linh hoạt khi di chuyển trên cành",
        },
        "verdict_vi": "Báo tuyết mạnh ở địa hình núi cao, báo gấm nổi bật ở leo cây và răng nanh dài.",
        "reality_note_vi": "Đây là so sánh thích nghi sinh học của hai loài mèo hoang, không cổ vũ đối đầu thật.",
        "debate_question_vi": "Bạn chọn cao thủ núi tuyết hay ninja trên cây?",
    },
    {
        "topic_type": "matchup_versus",
        "topic_key": "coyote_vs_black_backed_jackal",
        "subject_vi": "Sói Đồng Cỏ so tài Chó Rừng Lưng Đen",
        "subject_en": "Coyote versus black-backed jackal",
        "left": {
            "name_vi": "Sói Đồng Cỏ",
            "name_en": "Coyote",
            "height": "60 cm",
            "weight": "18 kg",
            "bite_force": "Thích nghi tốt",
            "edge_vi": "sống được gần đô thị, ăn đa dạng và di chuyển bền",
        },
        "right": {
            "name_vi": "Chó Rừng Lưng Đen",
            "name_en": "Black-backed jackal",
            "height": "45 cm",
            "weight": "10 kg",
            "bite_force": "Nhanh nhẹn",
            "edge_vi": "rất lanh lợi, sống tốt ở thảo nguyên và vùng khô hạn",
        },
        "verdict_vi": "Sói đồng cỏ nhỉnh ở sức bền và thích nghi đô thị, chó rừng lưng đen nổi bật ở sự nhanh nhẹn.",
        "reality_note_vi": "Đây là so sánh hai loài họ chó cỡ trung, không cổ vũ đối đầu thật.",
        "debate_question_vi": "Bạn chọn kẻ thích nghi đô thị hay tay săn thảo nguyên?",
    },
]


MYTH_VS_FACT_TOPICS = [
    {
        "topic_type": "myth_vs_fact",
        "topic_key": "owl_head_turn_myth_fact",
        "subject_vi": "Cú mèo quay đầu 360 độ thật không?",
        "subject_en": "Can owls turn their heads 360 degrees?",
        "visual_subject_en": "owl with flexible neck in moonlit forest",
        "hook_vi": "Nhiều người tưởng cú mèo quay đầu tròn 360 độ.",
        "main_fact_vi": "Sự thật: chúng xoay khoảng 270 độ nhờ cổ cực linh hoạt.",
        "twist_vi": "Mạch máu và cấu trúc cổ giúp não vẫn được cấp máu khi xoay mạnh.",
        "question_vi": "Bạn từng tin cú mèo xoay đủ 360 độ chưa?",
    },
    {
        "topic_type": "myth_vs_fact",
        "topic_key": "ostrich_head_in_sand_myth_fact",
        "subject_vi": "Đà điểu có thật sự vùi đầu xuống cát?",
        "subject_en": "Do ostriches bury their heads in sand?",
        "visual_subject_en": "ostrich on open savanna lowering its head near nest",
        "hook_vi": "Đà điểu không hề tự biến mình thành cây lau nhà cắm xuống đất.",
        "main_fact_vi": "Chúng cúi thấp để xoay trứng hoặc tránh bị chú ý từ xa.",
        "twist_vi": "Từ xa, cái đầu thấp sát đất dễ khiến người ta tưởng chúng vùi đầu.",
        "question_vi": "Bạn đã từng nghe lời đồn này ở đâu?",
    },
    {
        "topic_type": "myth_vs_fact",
        "topic_key": "chameleon_color_myth_fact",
        "subject_vi": "Tắc kè đổi màu chỉ để ngụy trang?",
        "subject_en": "Do chameleons change color only for camouflage?",
        "visual_subject_en": "chameleon displaying vivid colors on branch",
        "hook_vi": "Tắc kè không chỉ mặc áo tàng hình cho vui.",
        "main_fact_vi": "Màu sắc còn dùng để giao tiếp, dọa đối thủ và điều hòa nhiệt.",
        "twist_vi": "Một số màu rực rỡ xuất hiện khi chúng căng thẳng hoặc muốn ra tín hiệu.",
        "question_vi": "Bạn nghĩ màu nào của tắc kè trông bá đạo nhất?",
    },
]


GUESS_QUIZ_TOPICS = [
    {
        "topic_type": "guess_quiz",
        "topic_key": "guess_transparent_head_fish",
        "subject_vi": "Đố vui: con gì có đầu trong suốt?",
        "subject_en": "Guess the animal with a transparent head",
        "visual_subject_en": "barreleye fish with transparent dome head in deep sea",
        "hook_vi": "Một con cá nhìn xuyên qua chính cái đầu của mình.",
        "main_fact_vi": "Đáp án là cá mắt thùng, sống ở vùng biển sâu thiếu sáng.",
        "twist_vi": "Đôi mắt hình ống nằm trong vòm đầu trong suốt để nhìn con mồi phía trên.",
        "question_vi": "Nếu chỉ nhìn ảnh, bạn đoán ra con này không?",
    },
    {
        "topic_type": "guess_quiz",
        "topic_key": "guess_jaw_slingshot_shark",
        "subject_vi": "Đố vui: cá nào phóng hàm ra bắt mồi?",
        "subject_en": "Guess the shark with a slingshot jaw",
        "visual_subject_en": "goblin shark projecting its jaw in deep sea darkness",
        "hook_vi": "Có loài cá mập bắt mồi bằng một cú phóng hàm như lò xo.",
        "main_fact_vi": "Đáp án là cá mập yêu tinh, một gương mặt rất điện ảnh của biển sâu.",
        "twist_vi": "Hàm của nó bật ra phía trước để chụp con mồi trong tích tắc.",
        "question_vi": "Bạn thấy cú phóng hàm này ngầu hay hơi rén?",
    },
    {
        "topic_type": "guess_quiz",
        "topic_key": "guess_water_shooting_fish",
        "subject_vi": "Đố vui: cá nào bắn nước hạ côn trùng?",
        "subject_en": "Guess the fish that shoots water",
        "visual_subject_en": "archerfish shooting a stream of water at an insect",
        "hook_vi": "Một con cá biết dùng tia nước như súng bắn tỉa.",
        "main_fact_vi": "Đáp án là cá mang rổ, chuyên bắn côn trùng rơi khỏi cành.",
        "twist_vi": "Nó phải tính cả khúc xạ ánh sáng khi nhắm mục tiêu trên mặt nước.",
        "question_vi": "Bạn có bắn trúng nổi mục tiêu kiểu này không?",
    },
]


ONE_STORY_TOPICS = [
    {
        "topic_type": "one_story",
        "topic_key": "exploding_ant_last_defense_story",
        "subject_vi": "Câu chuyện lạ: kiến tự nổ để cứu tổ",
        "subject_en": "Exploding ant last defense story",
        "visual_subject_en": "exploding ant defending colony in rainforest macro scene",
        "hook_vi": "Có loài kiến chọn cách tự phá cơ thể khi tổ bị đe dọa.",
        "main_fact_vi": "Chúng phóng chất dính độc ra ngoài để làm chậm kẻ thù.",
        "twist_vi": "Cái giá là cá thể kiến hy sinh, nhưng cả đàn có thêm thời gian phòng thủ.",
        "question_vi": "Bạn thấy chiến thuật này anh hùng hay quá căng?",
    },
    {
        "topic_type": "one_story",
        "topic_key": "anglerfish_lantern_hunt_story",
        "subject_vi": "Câu chuyện lạ: chiếc cần câu phát sáng dưới biển sâu",
        "subject_en": "Anglerfish glowing lure story",
        "visual_subject_en": "deep sea anglerfish glowing lure in darkness",
        "hook_vi": "Trong bóng tối biển sâu, có kẻ đi săn bằng một chiếc đèn treo trước mặt.",
        "main_fact_vi": "Cá cần câu dùng mồi phát sáng để dụ con mồi lại gần miệng.",
        "twist_vi": "Ánh sáng ấy đến từ vi khuẩn cộng sinh sống trong bộ phận mồi nhử.",
        "question_vi": "Nếu thấy chiếc đèn này trong biển sâu, bạn có bơi lại gần không?",
    },
    {
        "topic_type": "one_story",
        "topic_key": "corpse_flower_fake_smell_story",
        "subject_vi": "Câu chuyện lạ: bông hoa giả mùi xác thối",
        "subject_en": "Corpse flower fake smell story",
        "visual_subject_en": "corpse flower blooming in humid rainforest",
        "hook_vi": "Có bông hoa mở tiệc bằng mùi không ai muốn ngửi lần hai.",
        "main_fact_vi": "Hoa xác thối tỏa mùi thịt phân hủy để dụ ruồi và bọ đến thụ phấn.",
        "twist_vi": "Mùi khó chịu lại là chiêu marketing cực hiệu quả trong tự nhiên.",
        "question_vi": "Bạn dám đứng gần bông hoa này bao lâu?",
    },
]


BEFORE_AFTER_TOPICS = [
    {
        "topic_type": "before_after",
        "topic_key": "caterpillar_to_butterfly_before_after",
        "subject_vi": "Trước và sau: sâu bướm hóa thành cánh bay",
        "subject_en": "Caterpillar to butterfly transformation",
        "visual_subject_en": "caterpillar chrysalis and butterfly transformation",
        "hook_vi": "Một cơ thể bò chậm có thể tái tổ chức thành cỗ máy bay mỏng manh.",
        "main_fact_vi": "Trước: sâu bướm ăn lá tích năng lượng trong cơ thể.",
        "twist_vi": "Sau: bướm trưởng thành có cánh, giác quan và nhiệm vụ sinh sản khác hẳn.",
        "question_vi": "Bạn thấy màn biến hình này giống phép thuật hay kỹ thuật sinh học?",
    },
    {
        "topic_type": "before_after",
        "topic_key": "tadpole_to_frog_before_after",
        "subject_vi": "Trước và sau: nòng nọc biến thành ếch",
        "subject_en": "Tadpole to frog metamorphosis",
        "visual_subject_en": "tadpole metamorphosis into frog in pond",
        "hook_vi": "Một sinh vật thở trong nước rồi lớn lên để nhảy lên bờ.",
        "main_fact_vi": "Trước: nòng nọc có đuôi và sống chủ yếu dưới nước.",
        "twist_vi": "Sau: ếch mọc chân, tiêu bớt đuôi và chuyển sang đời sống lưỡng cư.",
        "question_vi": "Bạn thích phiên bản nòng nọc hay ếch trưởng thành hơn?",
    },
    {
        "topic_type": "before_after",
        "topic_key": "jellyfish_life_cycle_before_after",
        "subject_vi": "Trước và sau: sứa đổi hình qua vòng đời",
        "subject_en": "Jellyfish life cycle transformation",
        "visual_subject_en": "jellyfish polyp to medusa life cycle glowing ocean",
        "hook_vi": "Sứa không chỉ trôi lững lờ; vòng đời của nó có nhiều pha đổi hình.",
        "main_fact_vi": "Trước: dạng polyp bám cố định như một sinh vật nhỏ dưới đáy.",
        "twist_vi": "Sau: dạng medusa bơi tự do với chuông và xúc tu quen thuộc.",
        "question_vi": "Bạn có bất ngờ vì sứa từng có giai đoạn bám một chỗ không?",
    },
]


def get_topic_by_index(index: int) -> dict:
    """Rotate evenly across all content formats."""
    topic_banks = [
        ("anatomy_infographic", ANATOMY_TOPICS),
        ("single_card", SINGLE_TOPICS),
        ("matchup_versus", MATCHUP_TOPICS),
        ("myth_vs_fact", MYTH_VS_FACT_TOPICS),
        ("guess_quiz", GUESS_QUIZ_TOPICS),
        ("one_story", ONE_STORY_TOPICS),
        ("before_after", BEFORE_AFTER_TOPICS),
    ]
    topic_group = index % len(topic_banks)
    group_index = index // len(topic_banks)
    topic_type, topics = topic_banks[topic_group]

    if group_index < len(topics):
        return deepcopy(topics[group_index])

    from app.generated_topic_service import get_generated_topic

    existing_topics = []
    for _, bank in topic_banks:
        existing_topics.extend(bank)
    existing_topics.extend(COMPARISON_TOPICS)
    return get_generated_topic(topic_type, group_index - len(topics), existing_topics)
